### ISSUE TITLE
Should this repo be .conf files?

### ISSUE THREAD

**Issue by AD7six** [h5bp/server-configs-apache#1]
This topic has come up in the past numerous times, some references:
- h5bp/html5-boilerplate#169
- h5bp/html5-boilerplate#876
- h5bp/server-configs#59

The use of an optimized`.htaccess` file is a great improvement compared to a standard apache install - but it is really just a stepping-stone solution to configuring apache appropriately.

It's kind of hard to cater for all uses but e.g. potential users of this repo include:
- frontend developers using html5-boilerplate
- users, wanting to optimize their site
- developers using html5-boilerplate as part of their project
- server-savvy users

Right now, the first two groups are catered for pretty well - you can drop in the `.htaccess` file into any project and it just works, and is an improvement. Perhaps they can't modify their apache config files, so it's the only solution that works for them  - though arguably shared hosting is less common than in the past, being replaced by vps servers, reducing the significance/relevance of this point.

The last two groups however are not catered for particularly well, a (general) developer using apache may be aware that they could avoid using `.htaccess` files but, through convenience of using the files provided probably won't. A user familiar with apache either won't use the repo at all (and these are the users who could provide the most benefit in terms of future contributions), or needs to spend some time integrating the provided rules into their existing config files.

Perhaps only the boilerplate repo should have/include the `.htaccess` file (generated by some build script).

One way or another, I feel that users should be guided to _the_ best way to use apache, not stopping just short of the finish line.

Comments?

**Comment by ianhobbs** [comment]
Great discussion, looking forward to using the .conf implementation and assessing performance gains.

**Comment by scottsb** [comment]
I know this thread has been open for a while, but I wanted to point out one drawback to the {{.conf}} approach: at least on CentOS 6.7 (the distro I'm currently working with), the include of {{conf.d/*.conf}} happens in the middle of the {{httpd.conf}} file. That means that anything specified by configuration directives will get overwritten by any defaults from the original file. While theoretically a user could move down the include line to the bottom of the {{httpd.conf}} file, at that point they no longer have the benefit of just dropping in a file and being ready to go.
