### ISSUE TITLE
If AddCharset utf-8 .jsonld is specified, Apache configtest fails.

### ISSUE THREAD

**Issue by kroko** [h5bp/server-configs-apache#100]
Hi,

If in virtual host definition the whole block is added

```
<IfModule mod_mime.c>
    AddCharset utf-8 .atom \
                     .bbaw \
                     .css \
                     .geojson \
                     .js \
                     .json \
                     .jsonld \
                     .manifest \
                     .rdf \
                     .rss \
                     .topojson \
                     .vtt \
                     .webapp \
                     .webmanifest \
                     .xloc \
                     .xml
</IfModule>
```

then Apache throws

```
The apache2 configtest failed. Not doing anything.
Output of config test was:
AH00526: Syntax error on line XXX of /etc/apache2/sites-enabled/XXX.conf:
Invalid command '. manifest', perhaps misspelled or defined by a module not included in the server configuration
Action 'configtest' failed.
```

So first I thought it has to do smth with that

```
AddType text/cache-manifest                         manifest
```

is not added above. However that was not the case.

Then I tried removing `.manifest \`. The same error was fired for `.rdf`, if that is removed then for `.rss`.
So whatever comes after `.jsonld \` throws the error.
**If `.jsonld \` is removed configtest passes.**

This is observed within virtual host directive. Main `apache2.conf` is vanilla.

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.3 LTS
Release:    14.04
Codename:   trusty
$ apache2 -v
Server version: Apache/2.4.7 (Ubuntu)
Server built:   Oct 14 2015 14:20:21
```

**Comment by XhmikosR** [comment]
Is this still an issue?

**Comment by kroko** [comment]
Of course, why would anything change regarding this? I'm still using

```
Server version: Apache/2.4.7 (Ubuntu)
Server built:   Jul 27 2017 15:20:24
```

**Comment by LeoColomb** [comment]
Are your ***sure*** there is no character (space, tab, ...) after the backslash on this line `.json \`?

**Comment by LeoColomb** [comment]
This issue is fairly old and there hasn't been much activity on it and I'm having trouble reproducing. Closing, but please _re-open_ if it still occurs.

**Comment by captain-geek** [comment]
Very similar issue:
```
AH00526: Syntax error on line 276 of /etc/apache2/github-optimizations.conf:
Invalid command '.vtt', perhaps misspelled or defined by a module not included in the server configuration
Action 'configtest' failed.
```

The configuration in question was:
```
<IfModule mod_mime.c>
    AddCharset utf-8 .atom \
                     .bbaw \
                     .css \
                     .geojson \
                     .ics \
                     .js \
                     .json \
                     .jsonld \
                     .manifest \
                     .markdown \
                     .md \
                     .mjs \
                     .rdf \
                     .rss \
                     .topojson \
                     .vtt \
                     .webapp \
                     .webmanifest \
                     .xloc \
                     .xml
</IfModule>
```

If I comment out the `.vtt \` or the `.topojson \` then the test passes ... and if I swap those two lines it works fine ... 

Just weird ...

**Comment by LeoColomb** [comment]
@captain-geek Thanks for your feedback. My comment/question is still valid: https://github.com/h5bp/server-configs-apache/issues/100#issuecomment-330257266

**Comment by captain-geek** [comment]
No, there is no character after the lines in question ... otherwise switching the order of those two lines wouldn't work ... 

This is one of those issues that shouldn't get too much attention unless more cases can be collected so that some pattern can be derived, agreed @LeoColomb
