### ISSUE TITLE
Updates?

### ISSUE THREAD

**Issue by haxcop** [h5bp/server-configs-apache#101]
HI I just wondering if this project still being supported and also does it works for Apache 2.4+?.

**Comment by Schweinepriester** [comment]
+1

**Comment by chriswells0** [comment]
I'm not a maintainer or committer of this project, but I can tell you that I use it with Apache 2.4.

**Comment by Llbe** [comment]
In setup.sh, there are setup code for 2.4.x.

**Comment by XhmikosR** [comment]
Everyone's welcome to submit PRs to keep things going :)

As for the question about 2.4.x, yes it works fine.
