### ISSUE TITLE
err_too_many_redirects when forcing https

### ISSUE THREAD

**Issue by pheliperocha** [h5bp/server-configs-apache#103]
When I use the rewrite to https

```
<IfModule mod_rewrite.c>
   RewriteEngine On
   RewriteCond %{HTTPS} !=on
   RewriteRule ^(.*)$ https://%{HTTP_HOST}/$1 [R=301,L]
</IfModule>
```

It return `err_too_many_redirects` error

And when I check the network tab in chrome developer tools I see has many 302 redirects..

I solve the problem change `RewriteCond %{HTTPS} !=on` to `RewriteCond %{HTTP:X-Forwarded-Proto} =http` and now It's all ok

**Comment by XhmikosR** [comment]
Yup, it's a known issue and will be fixed by #84. See also #52.
