### ISSUE TITLE
Project abandoned?

### ISSUE THREAD

**Issue by giovannipds** [h5bp/server-configs-apache#106]
Is this project abandoned? I see that the dev dependencies are not passing and the latest commit was more than one year ago (January of 2016). If it is, isn't better to warn that on the README file at least?

**Comment by giovannipds** [comment]
@alrra, @paulirish, @mathiasbynens, @mikealmond, @necolas hello?!

**Comment by paulirish** [comment]
yup, i'd say it's far to conclude this project is not maintained any longer.
i'll add a message on the readme.

**Comment by paulirish** [comment]
@giovannipds if you're interested in taking over as maintainer here, throw me an email.

**Comment by giovannipds** [comment]
@paulirish that's ok for me, I can give it a try. I just don't know if I'll have the whole knowledge needed, but I'll certainly interact through the issues and PRs. What you think?
