### ISSUE TITLE
Deny access to core dumps

### ISSUE THREAD

**Issue by Llbe** [h5bp/server-configs-apache#107]
I suggest denying access to core dumps, for obvious reasons (it's literally dumped memory).

Generally the CWD of an application should not be the public root and thus core dumps won't appear publicly accessible. But I think this is not a matter of how the core dump came into light. If it somehow got there it must be denied access to.

**The problem might be** how to properly identify core dumps. Please share any ideas.

- We should be able to identify them by MIME type for executable formats. But then we'll also deny other executables

- We can deny on common filenames (the name can be changed via /proc/sys/kernel/core_pattern on Linux)

- A combination of the above would probably be best. Ie denying access to any file (-f) with "core" in the name and of executable format

What I currently run with is (works for me, that's how my core dumps are named)

```
<FilesMatch "core\.\d+">
  Require all denied
</FilesMatch>
```

**Comment by LeoColomb** [comment]
> `core\.\d+`

This is really specific to your case, isn't it? I wonder if it's relevant for everyone and if this will not create a lot of false positives.

**Comment by jdreesen** [comment]
It seems to be somewhat relevant. There was an article on a German IT news website in june. The article is in german, of course and I'm not sure if the google tranlslation is understandable but here it is: https://translate.google.de/translate?hl=de&sl=de&tl=en&u=https%3A%2F%2Fwww.golem.de%2Fnews%2Fwebsicherheit-verraeterische-coredumps-im-webverzeichnis-1706-128377.html

**Comment by LeoColomb** [comment]
I'm closing this issue as inactive and difficult to document.
If you have more ressource on this case, or want to argument for the addition, please don't hesitate to continue the discussion below.
