### ISSUE TITLE
Blocking all .files in .htaccess causes Let's Encrypt install to fail

### ISSUE THREAD

**Issue by adamjansch** [h5bp/server-configs-apache#108]
I just tried to install Let's Encrypt through my webhost's cPanel but ran into a problem where the install failed because a file generated by the process was blocked by HTML5 Boilerplate's .htaccess file.

The LE auto-install process sets a file in /.well-known/acme-challenge, and in trying to access that file a 403 error is generated. When I commented out the RewriteRule (^\.|/\.) - [F] rule and re-ran the install succeeded. (I don't yet know if this will be a problem for renewing certificates.)

Can this filepath be whitelisted?

**Comment by QWp6t** [comment]
It's already whitelisted.

https://github.com/h5bp/server-configs-apache/blob/master/dist/.htaccess#L505-L528

```
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Block access to all hidden files and directories with the exception of
# the visible content from within the `/.well-known/` hidden directory.
#
# These types of files usually contain user preferences or the preserved
# state of an utility, and can include rather private places like, for
# example, the `.git` or `.svn` directories.
#
# The `/.well-known/` directory represents the standard (RFC 5785) path
# prefix for "well-known locations" (e.g.: `/.well-known/manifest.json`,
# `/.well-known/keybase.txt`), and therefore, access to its visible
# content should not be blocked.
#
# https://www.mnot.net/blog/2010/04/07/well-known
# https://tools.ietf.org/html/rfc5785

<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteCond %{REQUEST_URI} "!(^|/)\.well-known/([^./]+./?)+$" [NC]
    RewriteCond %{SCRIPT_FILENAME} -d [OR]
    RewriteCond %{SCRIPT_FILENAME} -f
    RewriteRule "(^|/)\." - [F]
</IfModule>
```

**Comment by adamjansch** [comment]
Too right, I must be running off an old version of 5.3.0 from https://html5boilerplate.com/.
