### ISSUE TITLE
optimize apache example.com => www.example.com

### ISSUE THREAD

**Issue by missjojo** [h5bp/server-configs-apache#11]
use

```
RewriteCond %{HTTP_HOST} !^www\. [NC]
RewriteCond %{SERVER_ADDR} !=127.0.0.1
```

replace

```
RewriteCond %{HTTP_HOST} !^www\..+$ [NC]
RewriteCond %{HTTP_HOST} !=localhost [NC]
RewriteCond %{HTTP_HOST} !=127.0.0.1
```

because:
1. save bits;
2. cover some non localhost virtual host such as a DIY `xx.dev` instead of `localhost` using hosts.

anyone agree?

**Comment by jaimergp** [comment]
I know this is is old, but... who would want a non-www to www redirect when accessing via server IP? I know it's a corner case, but I think there's no harm in adding another condition like:

    RewriteCond %{HTTP_HOST} !([0-9]{1,3}\.){3}[0-9]{1,3}

Correct me if I'm wrong please!

**Comment by mathiasbynens** [comment]
@jaimergp I expect everyone to be redirected to the one, true, canonical version of the URL they accessed. You wouldn’t want the site at the server IP to be indexed separately by search engines, would you?
