### ISSUE TITLE
Travis CI: auto-commit dist files is broken

### ISSUE THREAD

**Issue by XhmikosR** [h5bp/server-configs-apache#118]

**Comment by XhmikosR** [comment]
@alrra: maybe you could fix this? Or link to the procedure you followed. I think I have an idea, just want to be sure.

**Comment by alrra** [comment]
> I think I have an idea, just want to be sure.

@XhmikosR Quickly looking at the builds, it seems the SSH key will need to be set, and thus, recreated.

> Or link to the procedure you followed. 

See: https://github.com/alrra/travis-scripts/blob/e7a861590927325dd4c645512107e046917ee59d/doc/github-deploy-keys.md

**Comment by XhmikosR** [comment]
@alrra: thanks, that was my thought too :)

@LeoColomb: can you do this? I don't have a \*nix machine currently.

**Comment by LeoColomb** [comment]
@XhmikosR Yes, I can generate a new SSH key, but I don't have access to the repository settings.

**Comment by XhmikosR** [comment]
Yeah, only repo owners. @alrra can you sort this please?
