### ISSUE TITLE
npm package is not updated

### ISSUE THREAD

**Issue by LeoColomb** [h5bp/server-configs-apache#123]
Need an administrator to push the new version on npm.
Following #121 
@alrra from https://www.npmjs.com/package/apache-server-configs/access

**Comment by alrra** [comment]
You, @mathiasbynens, and @XhmikosR [should now have access to it](https://www.npmjs.com/package/apache-server-configs/access). :)

**Comment by LeoColomb** [comment]
Thanks, new version published! 🎉
