### ISSUE TITLE
redirect to https

### ISSUE THREAD

**Issue by sotnasemiolo** [h5bp/server-configs-apache#125]
I have ssl contracted in the main domain example.com, but I have other domains that I redirect to main. But, I'm having problems when I try to redirect https://example.com (does not have ssl) to https://example.com, when I try to do this it says "Your connection is not secure".
Would you help me?

**Comment by LeoColomb** [comment]
Hi @sotnasemiolo.
Sadly, this is nothing related with this repo `server-configs-apache`. You may review your configuration with your SSL certificate seller and/or your host to resolve your situation.
