### ISSUE TITLE
Add Referrer-Policy template

### ISSUE THREAD

**Issue by creopard** [h5bp/server-configs-apache#129]
There's a new security header available:
see https://scotthelme.co.uk/a-new-security-header-referrer-policy/ for details

e.g.:
```
# <IfModule mod_headers.c>
#     Header set Referrer-Policy: no-referrer-when-downgrade
# </IfModule>
```

**Comment by bke-daniel** [comment]
+1

**Comment by LeoColomb** [comment]
Thanks for your suggestion, @creopard, really good one!

Would you like to write a patch for this? We'd be more than happy to walk you through the steps involved. :rocket:

**Comment by creopard** [comment]
#130

**Comment by creopard** [comment]
Pull Request #130
