### ISSUE TITLE
Compress woff/woff2 fonts

### ISSUE THREAD

**Issue by creopard** [h5bp/server-configs-apache#131]
Web fonts are defined in htaccess:
```
    AddType font/woff                                   woff
    AddType font/woff2                                  woff2
```

but they are not compressed in the section    
```
<IfModule mod_filter.c>
AddOutputFilterByType DEFLATE
```

I think these types should be also added
```
AddOutputFilterByType DEFLATE [...]
                              "font/woff" \
                              "font/woff2" \
                              [...]
```

**Comment by jdreesen** [comment]
That's because WOFF files are already compressed and thus don't need to be compressed by the web server (see: https://en.wikipedia.org/wiki/Web_Open_Font_Format).

**Comment by LeoColomb** [comment]
Hello @creopard, thanks for opening this issue!
@jdreesen says everything, both WOFF and WOFF2 are already compressed by file format.
