### ISSUE TITLE
Expire text/plain sooner than 1 month

### ISSUE THREAD

**Issue by szepeviktor** [h5bp/server-configs-apache#132]
It would be useful to have robots.txt downloaded **daily**

**Comment by LeoColomb** [comment]
@szepeviktor This seems a really specific case.
Do you have a documentation/best practices document regarding `text/plain` and/or `robots.txt`?
If not, I would keep this rule as an "end-user" configuration (i.e. excluded of any general recommendation).

**Comment by szepeviktor** [comment]
https://developers.google.com/search/reference/robots_txt#handling-http-result-codes

> Caching
    A robots.txt request is generally cached for up to one day, but may be cached longer in situations where refreshing the cached version is not possible (for example, due to timeouts or 5xx errors). The cached response may be shared by different crawlers. Google may increase or decrease the cache lifetime based on max-age Cache-Control HTTP headers.

The same situation as for favicon,ico, your comment says: `cannot be renamed!`

**Comment by szepeviktor** [comment]
In the current state (default 1 month) changes in robots.txt may not take effect in a reasonable period of time.

**Comment by LeoColomb** [comment]
X-Ref: https://github.com/h5bp/html5-boilerplate/pull/1130

**Comment by LeoColomb** [comment]
Closing as inactive and answered in the issue linked above.
Please don't hesitate to continue the discussion below.

**Comment by szepeviktor** [comment]
Okay.
