### ISSUE TITLE
Serve pre-compressed files

### ISSUE THREAD

**Issue by midzer** [h5bp/server-configs-apache#134]
How about introducing a new section under web performance to allow apache to serve pre-compressed `.br` and/or `.gz` files?

In order to save CPU time on server side by skipping realtime compression, you can compress any test files lile `.html`, `.css`, `.js` etc in advance. This way reaction time for files to be delivered might improve, too.

I managed to get it to work in one of my .htaccess using https://httpd.apache.org/docs/2.4/mod/mod_deflate.html#precompressed as guideline. Would be happy to open a PR and talk about details.

**Comment by LeoColomb** [comment]
Thanks @midzer!
Would love to see a PR for this, definitely! 🚀
