### ISSUE TITLE
What about the `preload` flag in HSTS Header?

### ISSUE THREAD

**Issue by arturmamedov** [h5bp/server-configs-apache#137]
It's not recmend to add the `preload` flag to HSTS Header? I read it it here https://hstspreload.org and here https://www.owasp.org/index.php/HTTP_Strict_Transport_Security_Cheat_Sheet

What are you thinking about? Maybe it need to be included by default? Or in comment?

**Comment by LeoColomb** [comment]
> It's not recmend to add the preload flag to HSTS Header?

Yes, it is, but only when the addition is made with care.

> Maybe it need to be included by default? Or in comment?

Care means "not by default", so I don't think this is a good idea to add `preload` by default. That said, explaining this flag in comments is relevant and a really good idea! 👍 
Would you aim do this in a PR? Thx! 🎉

**Comment by LeoColomb** [comment]
Fixed by #128

**Comment by arturmamedov** [comment]
Sorry i was lost in deadlines, thank you!!!! :)
