### ISSUE TITLE
image/apng

### ISSUE THREAD

**Issue by Malvoz** [h5bp/server-configs-apache#138]
Consider adding the [`image/apng`](https://wiki.mozilla.org/APNG_Specification) MIME Type where it makes sense.

**Comment by LeoColomb** [comment]
Could explain how this addition would be relevant?
I mean is do you think this [non-official](https://www.iana.org/assignments/media-types/media-types.xhtml) MIME type is used enough to be included in a really generic guide/config?

**Comment by Malvoz** [comment]
As MDN  states: 

> It is intended to be a replacement for simple animated images that have traditionally used the GIF format, while adding support for 24-bit images and 8-bit transparency. APNG is a simpler alternative to MNG, providing a spec suitable for the most common usage of animated images on the Internet.

But of course if APNG does not gain traction, adding it would be redundant.

**Comment by LeoColomb** [comment]
Well, I don't know. APNG files are compatible with `image/png` type, that said the specific type is used at some places...

@XhmikosR thoughts?

---
Refs:
* Spec: https://wiki.mozilla.org/APNG_Specification
* Description: https://en.wikipedia.org/wiki/APNG
* MimeDB addition: https://github.com/jshttp/mime-db/pull/66
* Mozilla (creator) review: https://developer.mozilla.org/en-US/docs/Mozilla/Tech/APNG
* Review: http://fileformats.wikia.com/wiki/Animated_Portable_Network_Graphics
* PNG @ IANA registration: https://www.iana.org/assignments/media-types/image/png
* CanIUse: https://caniuse.com/#feat=apng
* Firefox addition: https://bugzilla.mozilla.org/show_bug.cgi?id=1160200
* Chrome addition: https://bugs.chromium.org/p/chromium/issues/detail?id=437662

**Comment by XhmikosR** [comment]
It's the first time I see it so I can't comment on it, apart from the fact that if its specs specify `image/apng` as the official mime type, there *should* be no issue adding it...

**Comment by hatzopoulos** [comment]
First time I've seen it too.

For what it's worth, the mime type has been commented out in https://github.com/apache/httpd/commit/e3d7909742c0a5462e6d583cfd05f17e271011f0, the default Apache httpd [mime.types file](https://github.com/apache/httpd/blob/e182716f7004b45c0ed4cce9a51a0985acb79451/docs/conf/mime.types#L1580). One simply has to uncomment it, or add it to their .htaccess file.

I don't see why they wouldn't add this but they added webp (which is non-standard according to that IANA list).
