### ISSUE TITLE
Block access to all hidden files and directories is not working outside .htaccess

### ISSUE THREAD

**Issue by ogmueller** [h5bp/server-configs-apache#139]
There is a rule in server-configs-apache/src/security/file_access.conf, which tries to prevent access to hidden files/directories:

```
<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteCond %{REQUEST_URI} "!(^|/)\.well-known/([^./]+./?)+$" [NC]
    RewriteCond %{SCRIPT_FILENAME} -d [OR]
    RewriteCond %{SCRIPT_FILENAME} -f
    RewriteRule "(^|/)\." - [F]
</IfModule>
```

That rule is only working within a .htaccess file, but using .htaccess is really slow. As the [documentation](http://httpd.apache.org/docs/current/mod/mod_rewrite.html#rewritecond) mentions, `SCRIPT_FILENAME` has constraints when using in context

> If used in per-server context (i.e., before the request is mapped to the filesystem) SCRIPT_FILENAME and REQUEST_FILENAME cannot contain the full local filesystem path since the path is unknown at this stage of processing.

This makes the rule unusable and "unsafe". The good thing is, that the [documentation](http://httpd.apache.org/docs/current/mod/mod_rewrite.html#rewritecond) suggests to solve this problem using a URL-based look-ahead feature:

> In order to obtain the full local filesystem path of the request in per-server context, use an URL-based look-ahead %{LA-U:REQUEST_FILENAME} to determine the final value of REQUEST_FILENAME.

There is another problem to this rule used in a non-htaccess context. Rewrite rules are not inherited per default (see [RewriteOptions](http://httpd.apache.org/docs/current/mod/mod_rewrite.html#rewriteoptions)). So if someone relies on it as a global security measure, but than adds a `<Directory>` or `<VirtualHost>`, files and directories are not protected. Maybe it makes sense to add an inherit option like `InheritDown` or `InheritDownBefore`. This option got introduces with Apache2 Version 2.4.8.

The new rule could look like this:

```
<IfModule mod_rewrite.c>
	RewriteEngine On
	<IfModule mod_version.c>
		<IfVersion >= 2.4.8>
			RewriteOptions InheritDown
		</IfVersion>
	</IfModule>
	RewriteCond %{REQUEST_URI} "!(^|/)\.well-known/([^./]+./?)+$" [NC]
	RewriteCond %{LA-U:REQUEST_FILENAME} -d [OR]
	RewriteCond %{LA-U:REQUEST_FILENAME} -f
	RewriteRule "(^|/)\." - [F]
</IfModule> 
```

**Comment by LeoColomb** [comment]
@ogmueller Thanks for this well-written report!

As discussed in old-but-still-relevant #1, these config files are not fully compatible for the server config level yet...

That said, a PR regarding your report will definitely help to move to the full compatibility. Then, could you make a PR for this?

Thanks again 👍

**Comment by broros** [comment]
What if you did this? will this work in the .access file and inside the /etc/apache2/* directory?

```
<Directory /var/www/>
        Options -Indexes
        Options FollowSymLinks
        AllowOverride None
        Require all granted
</Directory>
```
