### ISSUE TITLE
sed illegal option -- - in build.sh on macOS

### ISSUE THREAD

**Issue by tomkyle** [h5bp/server-configs-apache#140]
When running `bin/build/build.sh`, I get this “illegal option” message during the excution of the _apply_pattern_ function:

```
sed: illegal option -- -
usage: […]
 [✖] Create '.htaccess'
...
 [✖] Create '.htaccess' fixture
```

As far as I can see this a sed issue on macos. Workaround: Replace system's sed with a more modern one, gnu-sed. The _build.sh_ then succeeded:

```bash
$ brew install gnu-sed --with-default-names
...
🍺  /usr/local/Cellar/gnu-sed/4.4: 10 files ...
$ bin/build/build.sh
 [✔] Clean
 [✔] Create '.htaccess'
 [✔] Create '.htaccess' fixture
```

Question to sed magicians: Is there a way to avoid such additional installs?

My setup: OSX 10.11.6, homebrew bash4

**Comment by tomkyle** [comment]
**Caution! The above workaround may break other scripts.** 
An example on my computer are Frend Weinhaus' imagemagick scripts which produced "doubled" output – each line shows twice – after replacing _sed_ with the above _homebrew_ method. This is because Fred Weinhaus uses sed a lot to produce formatted output (such as help text)

After _unlinking_ the _homebrew_ GNU sed (i.e. restoring the default macOS BSD sed) everything worked fine again. _Linking_ again: Output doubled.

I am not sed expert enough to tell which command flags are responsible for that.

**Anyway, I found another solution: tweaking the sed parameters order.** 

**Here the original apply_pattern function:**
```bash
apply_pattern() {
    sed -e "s/%FilesMatchPattern%/$( \
        cat "${repo_root}/src/files_match_pattern" | \
        sed '/^#/d' | \
        tr -s '[:space:]' '|' | \
        sed 's/|$//' \
    )/g" --in-place "$1"
}
```

I found **if one shifts the _--in-place_ option to the beginnig of the sed call, and rename it to _-i_,** it seems to work fine:

```bash
apply_pattern () {
    sed -i -e "s/%FilesMatchPattern%/$( \
        cat "${repo_root}/src/files_match_pattern" | \
        sed '/^#/d' | \
        tr -s '[:space:]' '|' | \
        sed 's/|$//' \
    )/g" "$1"
}
```
Please, could someone with sed experience prove this? Thanks!

**Comment by LeoColomb** [comment]
Yup, your solution seems to be good enough! 🎉
