### ISSUE TITLE
[security] Prevent XXE attacks?

### ISSUE THREAD

**Issue by Malvoz** [h5bp/server-configs-apache#143]
XML External Entities are a top 10 security vulnerability at [OWASP](https://www.owasp.org/index.php/Category:OWASP_Top_Ten_Project).

Could the equivalent (or something similar) of [OWASP's PHP prevention method](https://www.owasp.org/index.php/XML_External_Entity_(XXE)_Prevention_Cheat_Sheet#PHP) be done in Apache?

Additional reading, blog post on XXE attacks:
https://hdivsecurity.com/owasp-xml-external-entities-xxe

**Comment by LeoColomb** [comment]
Thanks for your report @Malvoz!

This kind of attacks seems done on the application side, then nothing manage by the server configuration (at least for Apache).

Please comment or reopen if I'm wrong! 🙂
