### ISSUE TITLE
Remove text/javascript media type

### ISSUE THREAD

**Issue by midzer** [h5bp/server-configs-apache#144]
Hi all,

according to https://www.iana.org/assignments/media-types/media-types.xhtml and https://www.ietf.org/rfc/rfc4329.txt `text/javascript` is obsolete and should be replaced by `application/javascript`.

Taken from comment at https://stackoverflow.com/questions/876561/when-serving-javascript-files-is-it-better-to-use-the-application-javascript-or this proposal might break javascript execution for IE8 and below though. Currently only about 0.19% of users worldwide stick to those legacy browsers (via https://caniuse.com).

Is it time to remove this media type? What do you think about that?

**Comment by LeoColomb** [comment]
Refs:
* https://github.com/h5bp/server-configs-apache/commit/690f4ad6add3a3c2185641474e05378000a19d84#comments 
* https://github.com/h5bp/server-configs-apache/pull/124

**Comment by midzer** [comment]
Okay. I'll close this one for good.
