### ISSUE TITLE
Add WebAssembly module MIME type

### ISSUE THREAD

**Issue by LeoColomb** [h5bp/server-configs-apache#145]
```conf
AddType application/wasm wasm
```

Ref:
* https://webassembly.github.io/spec/core/binary/conventions.html
* https://developers.google.com/web/updates/2018/04/loading-wasm
* https://github.com/jshttp/mime-db/pull/97
* https://kripken.github.io/emscripten-site/docs/compiling/WebAssembly.html#web-server-setup

**Comment by laukstein** [comment]
Don't forget it to add also in `AddOutputFilterByType DEFLATE`, https://groups.google.com/forum/#!topic/emscripten-discuss/C7-i1gqWay4
