### ISSUE TITLE
Yahoo Link 404

### ISSUE THREAD

**Issue by hatzopoulos** [h5bp/server-configs-apache#150]
The linked to information doesn't exist anymore on https://developer.yahoo.com/blogs/ydn/pushing-beyond-gzipping-25601.html 

https://github.com/h5bp/server-configs-apache/blob/master/src/web_performance/compression.conf#L8

**Comment by LeoColomb** [comment]
Good catch! 👍 

A PR with an working link (either with the [archived page](https://web.archive.org/web/20160729061300/https://developer.yahoo.com/blogs/ydn/pushing-beyond-gzipping-25601.html) or the [original article](https://calendar.perfplanet.com/2010/pushing-beyond-gzipping/) (better?)) would be relevant.

Motivated @hatzopoulos? 🥇 😎
