### ISSUE TITLE
OWASP suggests protect .htaccess

### ISSUE THREAD

**Issue by Malvoz** [h5bp/server-configs-apache#152]
I've stumbled upon [similar code](https://perishablepress.com/improve-site-security-by-protecting-htaccess-files/) snippets before, [OWASP](https://www.owasp.org/index.php/Reviewing_The_Secure_Code_Environment) however suggests protecting the .htaccess file like so:

```
<Files .htaccess>
order allow,deny
deny from all
</Files>
```

Would this be redundant or useful? I would assume the majority of host providers protect .htaccess by default.

**Comment by hatzopoulos** [comment]
Hi, 

Yes your right, it's redundant now, Apache already has this in place. 

```ApacheConf
#
# The following lines prevent .htaccess and .htpasswd files from being 
# viewed by Web clients. 
#
<Files ".ht*">
    Require all denied
</Files>
```
from: https://github.com/apache/httpd/blob/e182716f7004b45c0ed4cce9a51a0985acb79451/docs/conf/httpd.conf.in#L169-L175

Check if yours does too by checking your apache conf files or just, try to access an .htaccess file on your server.
