### ISSUE TITLE
Deprecate P3P usage

### ISSUE THREAD

**Issue by LeoColomb** [h5bp/server-configs-apache#155]
P3P seems obsolete and not more really supported.

> Support for P3P 1.0 has been removed in Windows 10 and will have minimal ongoing servicing for previous versions of Windows. Recommended practice is to avoid deploying P3P privacy policies on your site.
> [[docs.microsoft.com](https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/compatibility/mt146424)]

---

P3P is used here: 

https://github.com/h5bp/server-configs-apache/blob/ea022f440ed4c50dbfa0acc6194c06ddefcbc666/src/internet_explorer/iframes_cookies.conf#L11

**Comment by XhmikosR** [comment]
Agreed, it should be removed. Not sure if it should be done in a major version bump, though.
