### ISSUE TITLE
Rewrite no www produces too many redirects

### ISSUE THREAD

**Issue by saibotk** [h5bp/server-configs-apache#160]
https://github.com/h5bp/server-configs-apache/blob/7eb30da6a06ec4fc24daf33c75b7bd86f9ad1f68/src/rewrites/rewrite_nowww.conf#L27

This produced output like: https://www.example.com/://example.com/://example.com/://example.com/://example.com/://example.com/://example.com/://example.com/://example.com/://example.com/

Until Chrome tells me the site tried to redirect too much,
i fixed it by surrounding it with quotes:
`RewriteRule ^ "%{ENV:PROTO}://%1%{REQUEST_URI}" [R=301,L] `

I cannot give any information about the apache version, because my hosting provider is not showing this  information. 
At least this exists in my version and i guess surrounding it with quotes is non-destructive and therefore can be safely implemented, to prevent this bug.

Thanks for the awesome template anyways ;) <3

**Comment by Malvoz** [comment]
Some hosting providers give webmasters an option of forcing SSL, if that is your case you could either remove the snippet in .htaccess or disable the setting in your hosting environment. I'm not sure that is what may have caused you the problem but I ran into a similar issue once.

**Comment by saibotk** [comment]
Ok so i looked into this,
and i cannot get the Apache version, since it is diabled by the hosting service and also i cannot find any information about that elsewhere.
My domain is no IDN or special in that way.
The log output does not tell me anything, besides the redirects appending the domain at each request until the client stops requesting the page.

Thanks for looking into this with me ;) 
I hope we can find the cause for this, so other people using this great template do not experience this too.

**Comment by LeoColomb** [comment]
Missing some important information to go further, try to contact your host provider.

Don't hesitate to come back if you find the reason or if you got some more details! 👍
