### ISSUE TITLE
Cache-bust all filetypes with far-future expire headers

### ISSUE THREAD

**Issue by Mako88** [h5bp/server-configs-apache#162]
Currently there are a number of filetypes set to use far-future expire headers, but their extensions are not included in the file-based cache-busting. Since they're set to be cached by default, they should also be set to be cache-busted by default.

Perhaps by default all files should be cache-busted (I can't think of any downsides to doing this):
`RewriteRule ^(.+)\.(\d+)\.(.+)$ $1.$3 [L]`

**Comment by LeoColomb** [comment]
Thanks for your issue, @Mako88!

Just to be sure I understand well, you're saying that some [mime-types expire declarations](https://github.com/h5bp/server-configs-apache/blob/7eb30da6a06ec4fc24daf33c75b7bd86f9ad1f68/src/web_performance/cache_expiration.conf#L15-L119) crossed with [there respectives extensions](https://github.com/h5bp/server-configs-apache/blob/7eb30da6a06ec4fc24daf33c75b7bd86f9ad1f68/src/media_types/media_types.conf) are not all available in [cache-busting](https://github.com/h5bp/server-configs-apache/blob/7eb30da6a06ec4fc24daf33c75b7bd86f9ad1f68/src/web_performance/filename-based_cache_busting.conf)?
Do you have specific usage for other extensions not currently cache-busting enabled?

**Comment by Mako88** [comment]
Yes, that's exactly what I'm saying :)

The one that made me aware of this issue was with .woff files. I use a plugin with my CMS that automatically converts links to cache-busting version (so something.whatever becomes something.12345.whatever, with the 12345 being the timestamp of the file...so if the file changes, the timestamp changes, and the file is cache-busted).

However, as I said, when linking a .woff webfont file the cache-busting didn't work because .woff isn't included in the list of extensions by default.

Is there any drawback to automatically cache-busting every filetype?

**Comment by LeoColomb** [comment]
> Is there any drawback to automatically cache-busting every filetype?

I don't know, but I don't like generalising shortcut accesses as it may allow bypassing refused accesses in certain conditions...

Thoughts @XhmikosR?
