### ISSUE TITLE
500 error when redirecting to domain

### ISSUE THREAD

**Issue by larrybotha** [h5bp/server-configs-apache#164]
Apache 2.4

A simple redirect from one domain to a primary domain serving a PHP site with h5bp's `.htaccess` was responding with a 500:

```htaccess
# example1.com
Redirect permanent / http://example.com
```

This is on a shared host, and no logs are kept for this error.

I narrowed the problem down to the **Document modes** section.

Only by matching for `html` / `php` files on the primary domain could I get redirects to work:

```htaccess
<FilesMatch "\.(htm|html|php)$">
  <IfModule mod_headers.c>

      Header set X-UA-Compatible "IE=edge"

      # `mod_headers` cannot match based on the content-type, however,
      # the `X-UA-Compatible` response header should be send only for
      # HTML documents and not for the other resources.

      <FilesMatch "\.(appcache|atom|bbaw|bmp|br|crx|css|cur|eot|f4[abpv]|flv|geojson|gif|gz|htc|ic[os]|jpe?g|m?js|json(ld)?|m4[av]|manifest|map|markdown|md|mp4|oex|og[agv]|opus|otf|pdf|png|rdf|rss|safariextz|svgz?|swf|topojson|tt[cf]|txt|vcard|vcf|vtt|wasm|webapp|web[mp]|webmanifest|woff2?|xloc|xml|xpi)$">
          Header unset X-UA-Compatible
      </FilesMatch>

  </IfModule>
</FilesMatch>
```

I know little about Apache, so I'm not sure this is the best way to do this, but it's at least working for my use-case.

---

What I don't understand is that `curl` would follow the redirects, but requests in the browser would 500.

**Comment by larrybotha** [comment]
@Malvoz yup, only using `FilesMatch` against `php`/`html` do I get a redirect from `redirecting-domain.com` to `primary-domain.com`.

The redirect statement in my original comment is the entirety of the `.htaccess` on `redirecting-domain.com`.

---

For the unmodified h5bp `.htaccess` on `primary-domain.com`:

- still get a 500 on `redirecting-domain.com`
- works as expected on `primary-domain.com`

---

Added quotes to the redirect on `redirecting-domain.com`'s `.htacccess`... and that 500s regardless of `.htaccess` on `primary-domain.com`! This server doesn't seem to handle quotes around redirects.

**Comment by LeoColomb** [comment]
OK, thanks for your reply. 
Closing for now, but please don't hesitate to come back here with more information.
