### ISSUE TITLE
File access  

### ISSUE THREAD

**Issue by broros** [h5bp/server-configs-apache#175]
This does not block access to directories without a default document
```
<IfModule mod_autoindex.c>
    Options -Indexes
</IfModule>
```

Need something like this to actually block access to directories 

```
<Directory /var/www/>
    Options -Indexes
   AllowOverride All
   Order allow,deny
   Allow from all
</Directory>
```

**Comment by LeoColomb** [comment]
Thanks for this report, @broros!

That said, I'm not sure to understand well...
We have [a test that check if a directory without default document return a 403](https://github.com/h5bp/server-configs-apache/blob/35edb91a8052f8663ca7e4a1a50d4bd799a7f21e/test/tests.js#L626-L636), and everything seems to work as expected.

Are you sure that directive is not overwritten?
Also:
* What is the exact answer?
* Is the directory the one where the `.htaccess` lives?

**Comment by broros** [comment]
I am not using the  .htaccess file

**Comment by LeoColomb** [comment]
Ah, but in that case your usage is currently out of scope of this repo. We plan to support top level configuration (#1), but this not the case yet.

For your usage, I think it depends on how and where `Options -Indexes` is used. It basically avoid to list the files of a directory, but depending of the rest of the configuration it may reply something anyway.
