### ISSUE TITLE
How to check if it has been applied?

### ISSUE THREAD

**Issue by alessandrofrancesconi** [h5bp/server-configs-apache#177]
I've copied all the server-config-apache directives into my apache2.config file, but I want to be sure that they have been actually applied. Is there a way to test if this config is actually working on my server?

**Comment by LeoColomb** [comment]
You may use [server-configs-test](https://github.com/h5bp/server-configs-test/stargazers) to test the full compliance of your server.

That said, please note that this repository is not ready for a root conf usage yet, see #1. You may experience some inconsistances.
