### ISSUE TITLE
Link to (missing/deleted) dist folder

### ISSUE THREAD

**Issue by mathiasbynens** [h5bp/server-configs-apache#178]
https://github.com/h5bp/server-configs-apache#usage

**Comment by LeoColomb** [comment]
Indeed, fixed.
Thanks!

**Comment by coliff** [comment]
Hi @LeoColomb ! When I make a build of HTML5Boilerplate with `gulp` - it removes the `dist\.htaccess`. Can you pls make a new release?
cc @roblarsen

**Comment by LeoColomb** [comment]
@coliff Not sure to understand, no git/npm release exclude `dist/.htaccess`. My error was only visible between two commits and was not released... 🙂
