### ISSUE TITLE
`Permissions-Policy` header

### ISSUE THREAD

**Issue by unindented** [h5bp/server-configs-apache#179]
When scanning my site through https://securityheaders.com/ I got flagged because I was missing a `Feature-Policy` header: https://scotthelme.co.uk/a-new-security-header-feature-policy/

Would you be interested in adding it to the template? I can make a PR if that's the case.

---

* Paper: https://w3c.github.io/webappsec-permissions-policy/
* MDN: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Feature-Policy
* CanIUse: https://caniuse.com/permissions-policy

**Comment by LeoColomb** [comment]
Thanks for opening this issue!
Before opening a PR, let's review the status of this header. 
Does this header follow a published standard?
What is its browser support?

**Comment by unindented** [comment]
> Does this header follow a published standard?

https://w3c.github.io/webappsec-feature-policy/

> What is its browser support?

Chrome and Safari atm: https://caniuse.com/#search=feature%20policy

**Comment by LeoColomb** [comment]
Thanks for these links! 👍 
That said, some concerns:
* W3C paper is a draft, not a released recommendation (yet);
* The support is very low and often partial when implemented.

I would suggest to wait for a more solid standard/support before adding a template here.

**Comment by unindented** [comment]
Sounds good to me. Thanks for considering!

**Comment by Malvoz** [comment]
When it comes to choosing which features to include in an example policy this [standardized features table](https://github.com/w3c/webappsec-feature-policy/blob/master/features.md#standardized-features) would come in handy. :)

**Comment by LeoColomb** [comment]
FYI, Feature Policy is deprecated and replaced by Permissions Policy.
https://caniuse.com/permissions-policy
