### ISSUE TITLE
image/tiff

### ISSUE THREAD

**Issue by rechandler12** [h5bp/server-configs-apache#180]
`image/tiff` is official image mime type. Consider adding `tiff?` to:
- cross-origin/images.conf
- web_performance/filename-based_cache_busting.conf

**Comment by LeoColomb** [comment]
Thanks for your report @rechandler12!
Can you provide some materials that support this MIME-type? IETF RFC, W3C recommendation, IANA record, etc.

**Comment by rechandler12** [comment]
`image/tiff` is correct instead of `image/tif`, my mistake sorry

- IANA list - https://www.iana.org/assignments/media-types/media-types.xhtml
- IANA - https://www.iana.org/assignments/media-types/image/tiff
- IETF  - https://tools.ietf.org/html/rfc3302
- RFC - https://www.rfc-editor.org/rfc/rfc3302.txt
- Apache mime.types - https://github.com/apache/httpd/blob/2.4.x/docs/conf/mime.types

**Comment by LeoColomb** [comment]
Thanks.
Do you think it is worth adding it? (@XhmikosR)

**Comment by XhmikosR** [comment]
I'm not very familiar with this this format apart from having some files over the years.

For web, I doubt this is a good choice, so IMO we shouldn't endorse bad formats.

**Comment by LeoColomb** [comment]
I would tend to agree, this format does not target web usage.
I'm closing this, but feel free to add comment below if have some web use cases.
