### ISSUE TITLE
X-UA-Compatible apply only on IE

### ISSUE THREAD

**Issue by laukstein** [h5bp/server-configs-apache#182]
https://github.com/h5bp/server-configs-apache/blob/64cb33d002b200a0e744f22f8419d960307a8f60/dist/.htaccess#L129

must apply only on IE, there are no use of it in other browsers.
Details in https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/compatibility/jj676915%28v%3dvs.85%29

**Comment by LeoColomb** [comment]
@laukstein See https://github.com/h5bp/server-configs-apache/pull/26#issuecomment-41156774.

**Comment by laukstein** [comment]
@LeoColomb, the warning was shown when used X-UA-Compatible. And actually IE is no longer supported, by Microsoft, that's way probably set that header only for IE or drop it.

@mathiasbynens, @alrra, do you think https://github.com/h5bp/server-configs-apache/pull/26#issuecomment-41156774 is still relevant? I doubt it.

**Comment by LeoColomb** [comment]
> is still relevant?

It is, even if I would love to drop that header.
Many many wrongly configured proxies are still used; many many outdated IE are still used.

**Comment by LeoColomb** [comment]
Also, if headers for the same request vary, and even is you add the `Vary` header, you may see some final user seeing not the expected case because of intermediate caches.

I'm closing this issue as invalid but feel free to add comments below to continue the discussion.
