### ISSUE TITLE
Directive "Header unset X-Powered-By" is not respected

### ISSUE THREAD

**Issue by GlassGruber** [h5bp/server-configs-apache#183]
Hey there, 
just as title, noting also that `mod_headers.c` _is_ enabled, and it's happening on a shared hosting server where I have no access to the PHP ini.  
After a couple testing and some fortunate google-fu, I was able to finally enforce it adding `always` to the mix

    Header always unset X-Powered-By

I can't really understand why the directive it is not respected without it, also there are no redirects in the request. 

In the [docs ](https://httpd.apache.org/docs/current/mod/mod_headers.html) I wasn't able to find much about possible side effects for this option.  

So I'm wondering if it could be a sensed default to insert for this specific rule, or maybe put a notice in the comments suggesting this approach if the directive is not working.

I can make a PR if requested.

Thank you!

**Comment by LeoColomb** [comment]
From [httpd docs](https://httpd.apache.org/docs/current/mod/mod_headers.html#header):

> You're modifying or removing a header generated by a CGI script or by mod_proxy_fcgi, in which case the CGI scripts' headers are in the table corresponding to `always` and not in the default table.

So I think you're right.

> I can make a PR if requested.

Sure! 😃
