### ISSUE TITLE
`Cache-Control: no-transform` redundant w/ TLS?

### ISSUE THREAD

**Issue by Malvoz** [h5bp/server-configs-apache#185]
Is `cache-control: no-transform` redundant over HTTPS?

> **Better to focus on https** which cannot be modified in flight [...]

<i>https://meta.discourse.org/t/add-cache-control-no-transform-http-header/25152/3</i>

> Some mobile providers will compress or alter content, in particular images, to save bandwidth when re-transmitting content over cellular networks. This could break digital signatures in some cases. "no-transform" will prevent that (but again: **doesn't matter for SSL** [...]

<i>https://isc.sans.edu/forums/diary/The+Security+Impact+of+HTTP+Caching+Headers/17033/</i>

As suggested by some folks in their articles, "payload transformations" aren't possible over HTTPS. This sounds logical, but I am unsuccessful in confirming this.

In https://tools.ietf.org/html/rfc7234#section-5.2.1.6 I'm unable to traverse up to find information on payload transformation in relation to the HTTP/HTTPS protocol.

<hr>

If it is the case that `no-transform` is redundant over HTTPS, then this:

https://github.com/h5bp/server-configs-apache/blob/e12ae05c4ae690e36386de0efc2cfc0186f2f4f2/src/web_performance/content_transformation.conf#L21

Could be (or only/and with a note stating no need to use if HTTPS?):

```
Header merge Cache-Control "no-transform" "expr=%{HTTPS} != 'on'"
````

**Comment by LeoColomb** [comment]
Good catch.
Actually, does the `no-transform` still useful?

**Comment by Malvoz** [comment]
> (Also: https://csswizardry.com/2019/03/cache-control-for-civilians/#no-transform)

> If you’re running over HTTPS—which you should be—then intermediaries and proxies can’t modify payloads anyway, so no-transform would be ineffective.

Everyone seems to agree with that statement!

If it is still useful? H5BP doesn't default to TLS configs (which is debatable), but today more than not - developers use TLS for their webistes. Which renders `no-transform` useless as we've established in our _extensive_ reasearch. :)

**Comment by LeoColomb** [comment]
> H5BP doesn't default to TLS configs

I plan to, while working on #1. I've done it already for nginx configs. But we can't enable them by default since it require certificates we don't have.

> our _extensive_ reasearch

😎 

---
@XhmikosR Thoughts?

**Comment by LeoColomb** [comment]
Side note: if we keep it, the rfc link needs to be updated to https://tools.ietf.org/html/rfc7234#section-5.2.1.6

**Comment by XhmikosR** [comment]
I don't have an opinion myself since I only use HTTPS in all my projects.

**Comment by LeoColomb** [comment]
Same for me. I think we can consider dropping it.

**Comment by markwoon** [comment]
While I'm not advocating reverting this change, I wanted to point out that Google's Lite Mode (previously known as Data Saver) does work on https, and does respect `no-transform`.

Reference: https://venturebeat.com/2019/04/23/google-kills-chrome-data-saver-extension/

**Comment by Malvoz** [comment]
Thanks for the information @markwoon.

The IETF [section 5.7.2](https://tools.ietf.org/html/rfc7230#section-5.7.2) on transformations refers to proxies only, and the articles I listed to initially all refers to "proxies cannot modify payloads over HTTPS". However, in comment 8 in https://bugs.chromium.org/p/chromium/issues/detail?id=941948#c8 clarifies: <q>For HTTPS pages, a Lite page does NOT use a proxy.</q> which further suggests Google's Lite Mode is indeed able to transform payloads, even over HTTPS.

This certainly favors keeping https://github.com/h5bp/server-configs-apache/blob/master/src/web_performance/content_transformation.conf as is. Currently, the snippet applies to all content, while the Google Bot only looks for `cache-control: no-transform` in `text/html` for opt-outs. I don't think it's necessary to change anything since that's "just" Google.

From what I've read, these transformations may apply to any website really. Not only slow websites, but rather weather the user is on a slow client or not. If you have a Google account, you can use the [Transcoder test tool](https://www.google.com/webmasters/tools/transcoder#url=www.example.com) or visit Weblight with your url in the `u` query string parameter, such as https://googleweblight.com/i?u=https://www.html5boilerplate.com to test the effects of such transformations.

Useful articles:
https://support.google.com/webmasters/answer/6211428?hl=en
https://blog.chromium.org/2019/04/data-saver-is-now-lite-mode.html
https://blog.chromium.org/2019/03/chrome-lite-pages-for-faster-leaner.html

**Comment by LeoColomb** [comment]
Thanks for these extensive review guys!

Although I personally am not in favor of using these kind of weird tools, I don't feel confortable advocating against data savers & co usage.
I mean they are build for something useful and can be very relevant in some countries/situations, are we sure we should promote bypassing these technology?

The scenario is very different from the original arguments focusing advertisements or trackers addition.

**Comment by markwoon** [comment]
I'm going to abstain from what the default should be.  I'm on slow connections often enough to know how painful that can be, but I also *hate* debugging caching problems.

I do vote for this getting documented.  

People should decide for themselves how they want their site to behave.

**Comment by Malvoz** [comment]
@LeoColomb 

> I don't feel confortable advocating against data savers

While I agree that data saving is important (in fact [I proposed a CSS media query](https://github.com/w3c/csswg-drafts/issues/2370) allowing developers to serve lighter content based on that preference) I think **developers should be wary** of the fact that their content may be modified unless having opted out from it, since these transformations may disable scripts, styles and even form submissions.

> are we sure we should promote bypassing these technology?

No not promoting it, but more so what @markwoon said. Until yesterday I had no idea my content was subject to transcoding.

But I agree, in most cases content transformation (certainly under Google's Web Light heuristics, e.g.: user is on a 2G connection, Google Bot finds the page will take more than 5 seconds to load) will be useful and developers should be careful opting-out.

**Comment by LeoColomb** [comment]
> developers should be wary

👍 

> developers should be careful opting-out

That's my main concern. 😉 
But let's keep it for now, indeed.
