### ISSUE TITLE
Ensure HTTP headers are applied to the correct Content-Type

### ISSUE THREAD

**Issue by Malvoz** [h5bp/server-configs-apache#187]
It was brought to my attention that for example, the [CSP header](https://github.com/h5bp/server-configs-apache/blob/master/src/security/content-security-policy.conf) should be sent for other resources such as XML and workers.

(While we could send any given HTTP header in all responses, it'll contribute to header bloat, and for other headers it may even cause issues)

https://github.com/w3c/webappsec/issues/520
https://github.com/webhintio/hint/issues/2342

**Comment by LeoColomb** [comment]
Well, let's see the conclusions of these issues before concrete action.
I look forward to webhint answer.

**Comment by Malvoz** [comment]
webhint.io settled on setting CSP for `text/html|text/xml|application/xhtml+xml|text/javascript|application/pdf|image/svg+xml` in https://github.com/webhintio/hint/pull/2618, because they're all able to execute scripts in their context (except for JS, but it's the easiest way to set [CSP for workers](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy#CSP_in_workers)).

So adjusting the pattern to match the types in [`media_types.conf`](https://github.com/h5bp/server-configs-apache/blob/master/src/media_types/media_types.conf): remove `xhtml+xml` and change `text/xml` to `application/xml` (both are valid but the latter matches what H5BP already does).

which equals:
`text/html|application/xml|text/javascript|application/pdf|image/svg+xml`

However `application/pdf` is currently not handled by `media_types.conf`. Should it be? IMO yes.

**Comment by LeoColomb** [comment]
OK.

```regex
text\/(html|javascript)|application\/pdf|xml
```

is sufficient or are false positives for other xml relative types undesirable?

**Comment by Malvoz** [comment]
Covering all cases of XML is probably even better. Yes it's sufficient IMO.

**Comment by LeoColomb** [comment]
Alright. Can't wait for your PR! 😉

**Comment by LeoColomb** [comment]
Closed via #200
