### ISSUE TITLE
`Access-Control-Allow-Origin` pointing to an origin should include `Vary: Origin`

### ISSUE THREAD

**Issue by Malvoz** [h5bp/server-configs-apache#192]
When `Access-Control-Allow-Origin` points to a URL rather than `*`, then `Vary: Origin` should be sent along with the response.

Sources:
- https://fetch.spec.whatwg.org/#cors-protocol-and-http-caches
- https://w3c.github.io/webappsec-cors-for-developers/#use-vary
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin#CORS_and_caching
- https://textslashplain.com/2018/08/02/cors-and-vary/

All of the [CORS configs](https://github.com/h5bp/server-configs-apache/tree/master/src/cross-origin) use `*` in the examples. But if anything, there could potentially be a note of this in [`requests.conf`](https://github.com/h5bp/server-configs-apache/blob/master/src/cross-origin/requests.conf)? Or something better than just a note?

**Comment by LeoColomb** [comment]
A note seems to be a good start. 👍 

Maybe the note can be attached to a commented out directive:

```apacheconf
# (1)
# Header append Vary Origin
```

**Comment by Malvoz** [comment]
A note would be good indeed.

Going further, `access-control-allow-origin` can only include 1 origin at max, so developers must return different values based on the requesting origin and this is not a straight forward implementation unless you really know your apache :P 

You would have to do something along the lines of https://stackoverflow.com/a/1850482/9314312
