### ISSUE TITLE
Default HSTS to secure connections only - per advise in doc

### ISSUE THREAD

**Issue by Malvoz** [h5bp/server-configs-apache#194]
https://github.com/h5bp/server-configs-apache/blob/feb3a3689f83fdd4727276d6da5a184ef5caff37/src/security/strict-transport-security.conf#L44

Since [it is advised](https://github.com/h5bp/server-configs-apache/blob/feb3a3689f83fdd4727276d6da5a184ef5caff37/src/security/strict-transport-security.conf#L30) to only set this header over a secure connection, should this line not include ` env=HTTPS` (alternatively `"expr=%{HTTPS} == 'on'"`) by default? Or rather, delete this line altogether.

**Comment by LeoColomb** [comment]
I think the main reason is the we prefer sending STS header on any connection over risking a never-sent situation.
That's why the two other example lines.

**Comment by Malvoz** [comment]
Gotcha!

> never-sent situation

Is this explicitly due to the fact that `"expr=%{HTTPS} == 'on'"` OR `env=HTTP` historically speaking hasn't been compatible in certain  server environments for some people?

Or is this just to be safe in case Apache just "magically" does not respond with the header even though it should over HTTPS as we're telling it to?

**Comment by LeoColomb** [comment]
Good question.
Actually we probably can rewrite this part: we have have removed support for versions 2.3- since its addition and `"expr=%{HTTPS} == 'on'"` should be always compatible.

PR? 😉

**Comment by Malvoz** [comment]
@LeoColomb Sure, I'll get to it soon :)
