### ISSUE TITLE
`X-XSS-Protection` removal?

### ISSUE THREAD

**Issue by Malvoz** [h5bp/server-configs-apache#198]
- Chrome has an "[Intent to Deprecate and Remove the XSS Auditor](https://groups.google.com/a/chromium.org/forum/#!msg/blink-dev/TuYw-EZhO9g/blGViehIAwAJ)".
- Firefox have not (to my surprise), and [will not implement `X-XSS-Protection`](https://bugzilla.mozilla.org/show_bug.cgi?id=528661).
- Edge [retired their XSS](https://blogs.windows.com/windowsexperience/2018/07/25/announcing-windows-10-insider-preview-build-17723-and-build-18204/) filter last year:

> We are retiring the XSS filter in Microsoft Edge beginning in today’s build. Our customers remain protected thanks to modern standards like Content Security Policy, which provide more powerful, performant, and secure mechanisms to protect against content injection attacks, with high compatibility across modern browsers.

FWIW, as a result https://securityheaders.com/ now recommends CSP instead as well.

If sites use CSP without allowing `unsafe-inline` for scripts then `X-XSS-Protection` has very little value.

**Comment by Malvoz** [comment]
@LeoColomb in https://github.com/h5bp/server-configs-apache/issues/154#issuecomment-472388627 you said there are no plans to drop support for IE.

Because IE does not implement CSP (only `X-Content-Security-Policy` which shouldn't be endorsed) then perhaps this (and `X-Frame-Options`) shouldn't be removed until IE support is dropped as well.

**Comment by LeoColomb** [comment]
I would really love to drop IE support, but I'm not sure we can, and I really don't want to make this decision without further approvals (@XhmikosR @mathiasbynens).

**Comment by XhmikosR** [comment]
Well, it doesn't hurt anyone and unfortunately IE still has a market share quite big in some places.

If this were to happen, it should be accompanied by a major version bump along with further cleanup in stuff that can be removed.

Personally, I aim for the biggest coverage, just my 2 cents.

**Comment by cnleo** [comment]
Another 2 cent:
As far [securityheaders.com/?q=github.com](https://securityheaders.com/?q=https%3A%2F%2Fgithub.com%2Fh5bp%2Fserver-configs-apache%2Fissues%2F198&hide=on&followRedirects=on) listed as “green”, so why do not let them there. You know, more “green” feels good. Even github still used it.
I am not sure about browser forks with the older chromium/webkit engines that have x-xss-protection but no or limited CSPv2/CORS support. What about Safari/iOS and TV Browser and Android/webview? Take a look to [caniuse.com](https://caniuse.com) especially the notes and known issues for [CSP](https://caniuse.com/#search=CSP)/[CORS](https://caniuse.com/#search=CORS). But yes, the older IEs (8 up to and include 11) are still the most hit the fan, why it should not be removed so quickly. And the payload for that is, in my opinion, excessive minimal. ;D

OT: By the way, hash and nonce of CSP for Edge is at the moment broken:
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/13246371/

https://caniuse.com/#search=CSP
https://caniuse.com/#search=CORS
