### ISSUE TITLE
rewrite to https for proxy users

### ISSUE THREAD

**Issue by long76** [h5bp/server-configs-apache#201]
```ApacheConf
RewriteCond %{HTTPS} !=on
RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]
```

never ending 301 move even if url have https

```ApacheConf
RewriteCond %{HTTP:X-Forwarded-Proto} !https
RewriteCond %{HTTPS} off
RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]
```

move 301 once

**Comment by LeoColomb** [comment]
Thanks for opening this issue, @long76.

I'm not sure to follow: why did you activate HTTPS redirection if your server is behind an HTTP proxy?

**Comment by long76** [comment]
@LeoColomb i think that my sever(hosting) not behind an HTTP proxy but without `RewriteCond %{HTTP:X-Forwarded-Proto} !https` is doesn't worked.
you can suggest better solution?

**Comment by LeoColomb** [comment]
> it doesn't worked

If it did not work, then you have a proxy or something between clients and your server.

@XhmikosR What do you think?

**Comment by LeoColomb** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please _re-open_ if it still occurs or if you have more information to provide.
