### ISSUE TITLE
Add MIME types for WebPackage

### ISSUE THREAD

**Issue by Malvoz** [h5bp/server-configs-apache#205]
[Web Packaging](https://github.com/WICG/webpackage) "comes in several layers":

- Bundled HTTP Exchanges (Web Bundles):
  https://datatracker.ietf.org/doc/html/draft-ietf-wpack-bundled-responses

  `.wbn` file extension = `application/webbundle`

- Signed HTTP Exchanges:
  https://tools.ietf.org/html/draft-yasskin-http-origin-signed-responses

  `.sxg` file extension = `application/signed-exchange`
  
  (also defines `application/cert-chain+cbor` but no definition of a file extension ("N/A"), however there are examples in the wild of `cert.cbor` files with this media-type. Perhaps it'll be a convention in the future...)

**Comment by LeoColomb** [comment]
For ref: https://caniuse.com/#feat=sxg

**Comment by LeoColomb** [comment]
* Web Bundles
  IETF draft going to the right direction but still not approved.
  * https://datatracker.ietf.org/doc/draft-ietf-wpack-bundled-responses/

* Signed HTTP Exchanges
  RFC abandoned, support quite low, Mozilla rejection.
  * https://datatracker.ietf.org/doc/draft-yasskin-http-origin-signed-responses/
  * https://caniuse.com/sxg
  * https://mozilla.github.io/standards-positions/#http-origin-signed-responses

**Comment by bigsnow500** [comment]
Hi I need a 12-key phrase to get bitcoin
