### ISSUE TITLE
X-Frame-Options don't mention anything about CSP

### ISSUE THREAD

**Issue by ayumi-cloud** [h5bp/server-configs-apache#208]
Google and a few others have said they stopped using the `X-Frame-Options` header a while ago and that users should switch over to using CSP.

See here link (Google dropped support in Chrome 52): https://developers.google.com/web/updates/2016/06/chrome-52-deprecations#remove_support_for_x-frame-options_in_tags

It contains the following link: https://owasp.org/www-community/Clickjacking

Which I quote:

> Sending the proper Content Security Policy (CSP) frame-ancestors directive response headers that instruct the browser to not allow framing from other domains. (This replaces the older X-Frame-Options HTTP headers.)

Link: https://www.w3.org/TR/CSP3/#directive-frame-ancestors

There is no mention of that in the X-Frame-Options section! File location here: https://github.com/h5bp/server-configs-apache/blob/master/src/security/x-frame-options.conf

---

What I'm saying is, you say it in the csp section, but you should also mention it in the X-Frame-Options section as well.

**Comment by laukstein** [comment]
See here what response I got regarding it https://github.com/securityheaders/securityheaders-bugs/issues/54

**Comment by LeoColomb** [comment]
Thanks for opening this issue @ayumi-cloud.
Please use the search feature before opening a new issue, in our case you can find a review of `X-Frame-Options` in #154.

**Comment by ayumi-cloud** [comment]
@LeoColomb See image:

![image](https://user-images.githubusercontent.com/57409060/73104535-7e47e180-3eee-11ea-825b-c12755d98990.png)

There is no duplicate issue here!

I'm saying you give NO MENTION OF CSP IN YOUR DESCRIPTION HERE!

**Comment by LeoColomb** [comment]
Well XFO is not CSP, so this is not that surprising...
Anyway, documentation is always improvable, don't hesitate to open a pull request with you suggestions.

**Comment by ayumi-cloud** [comment]
> Well XFO is not CSP, so this is not that surprising...

Strange as you wrote this:

> superseded by for the CSP addition.

Comment link: https://github.com/h5bp/server-configs-apache/issues/154#issuecomment-472388627

I rather not submit a pull request for you. Instead we prefer just to hard fork this repo (due to poor management).
