### ISSUE TITLE
Drop support for Internet Explorer

### ISSUE THREAD

**Issue by summercms** [h5bp/server-configs-apache#210]
File location: https://github.com/h5bp/server-configs-apache/blob/master/src/internet_explorer/x-ua-compatible.conf

I quote your repo:

> Force Internet Explorer 8/9/10 to render pages in the highest mode available in the various cases when it may not.

and

> Starting with Internet Explorer 11, document modes are deprecated.

Windows has said the following:

> ***Internet Explorer (IE) 10 will reach end of support on January 31, 2020. From this point forward, IE 11 will be the only supported version of Internet Explorer...

Link: https://support.microsoft.com/en-gb/help/17454/lifecycle-faq-internet-explorer

Therefore surely, the above file should be dropped in 6 days time?

---

Also Microsoft Edge has moved from EdgeHTML to now using Google's Chromium and so even Edge doesn't use this header anymore.

Quoted from their website:

> The new Microsoft Edge  is based on Chromium and was released on January 15, 2020.

Note: That date has now passed.

Link: https://support.microsoft.com/en-gb/help/4501095/download-the-new-microsoft-edge-based-on-chromium

**Comment by LeoColomb** [comment]
Thanks for this issue @ayumi-cloud.
That said, once again, we would appreciate you search already existant issue **before** opening a new one. Here, you should have continue the discussion on #182.

Reaching end of support is far from meaning no more existant on Earth. Market share still show a relatively large usage of IE especially in some regions.

**Comment by LeoColomb** [comment]
@ayumi-cloud One year later, IE usage has shifted a lot.
Now we are safe to deprecate Internet Explorer 10 relative rules.
