### ISSUE TITLE
Why do we need <Directory> inside <Virtualhost>?

### ISSUE THREAD

**Issue by fazliddin** [h5bp/server-configs-apache#211]
I am a little confused. What is difference between
```
<VirtualHost *:80>

    # (1)
    ServerName example.com
    ServerAlias www.example.com

    # Path for static files
    DocumentRoot "/var/www/example.com/public"

    # (1)
    Include h5bp/rewrites/rewrite_nowww.conf

    # Include the basic h5bp config set
    Include h5bp/basic.conf

    <Directory "/var/www/example.com/public">
        Require all granted
    </Directory>

</VirtualHost>
```
and
```
<VirtualHost *:80>

    # (1)
    ServerName example.com
    ServerAlias www.example.com

    # Path for static files
    DocumentRoot "/var/www/example.com/public"

    # (1)
    Include h5bp/rewrites/rewrite_nowww.conf

    # Include the basic h5bp config set
    Include h5bp/basic.conf

     Require all granted

</VirtualHost>
```

https://github.com/h5bp/server-configs-apache/blob/master/vhosts/templates/no-ssl.example.com.conf

**Comment by LeoColomb** [comment]
Thanks for opening this ticket @fazliddin.
Your second example might not work as [`Require` is usable in directory or `.htaccess` contexts only](https://httpd.apache.org/docs/2.4/mod/mod_authz_core.html#require).

**Comment by fazliddin** [comment]
Thank you for fast answer. Where can we find list of rules which require to be written inside Directory?
it is my vhost
```
<VirtualHost *:80>
<Directory /var/www/>
        php_admin_value open_basedir "/var/www/mysite"
 </Directory>

    <Directory /var/www/mysite/vhost>
        php_admin_value session.referer_check "mysite.com"
    </Directory>
</VirtualHost>
```
Should above be written inside Directory?
How about url rewrites?

**Comment by fazliddin** [comment]
I got, we need to look Context field in doc: https://httpd.apache.org/docs/2.4/mod/directive-dict.html#Context

**Comment by LeoColomb** [comment]
> look Context field

That's it! 🙂 
Closing.
