### ISSUE TITLE
Wrong IfModule directive in line 29 of ssl_engine.conf

### ISSUE THREAD

**Issue by lourdas** [h5bp/server-configs-apache#214]
Line 29 in ssl/ssl_engine.conf writes:

`<IfModule mod_socache_dbm.c>`

but line 30 writes:
`SSLSessionCache "shmcb: ....`

Since it appears that the shmcb cache provider is used, shouldn't line 29 be:

`<IfModule mod_socache_shmcb.c>` ?

**Comment by LeoColomb** [comment]
Thanks for opening this ticket @lourdas, really good catch! 👍 

Would you aim to open a pull request?
