### ISSUE TITLE
Missing h5bp folder?

### ISSUE THREAD

**Issue by otherjoel** [h5bp/server-configs-apache#216]
The README and `httpd.conf` refer to a `h5bp` subfolder that contains various additional configuration files. But this subfolder does not exist in the repo and is not created by any build process described in the docs or that I can find.

The contents of the `src` subfolder seem to match what `httpd.conf` expects to find in the missing `h5bp` subfolder.

**Comment by LeoColomb** [comment]
Closing via 9cb2763d7f5e3fce984bfdea903e9df61cdf4bcd

Thanks for your report, it is now in live with documentation.

**Comment by otherjoel** [comment]
Thanks!
