### ISSUE TITLE
Incorrect location for in-place configuration files

### ISSUE THREAD

**Issue by otherjoel** [h5bp/server-configs-apache#218]
The included `httpd.conf` refers to a `conf/mime.types` file that does not exist:

https://github.com/h5bp/server-configs-apache/blob/9cb2763d7f5e3fce984bfdea903e9df61cdf4bcd/httpd.conf#L116

The README directs users to replace the entire Apache configuration folder with the contents of this repo, and set the `ServerRoot` directive to this same folder. But there is no `conf/` folder in this repo and no `mime.types` file within it.

On CentOS, the file exists elsewhere (`/etc/mime.types`), so the line can simply be edited to reflect that.

Pointing `TypesConfig` to a non-existent file will pass `apachectl configtest` (assuming the rest of the conf files are correct) but starting the Apache service will fail with an unspecified error.

The quick solution would be to update `README` and the comments in `httpd.conf` to reflect this. Another idea would be to include `conf/mime.types` in this repo, although this might mean work to maintain it in the future.

---

There is a similar problem with the `modules` subfolder, which exists in the “stock” Apache2 config folder that comes with most distros, but not in this repo which is intended to replace the stock folder:

https://github.com/h5bp/server-configs-apache/blob/9cb2763d7f5e3fce984bfdea903e9df61cdf4bcd/httpd.conf#L14-L19

In CentOS 8, for example, the folder containing Apache configs includes a `modules` that is a symlink to `/usr/lib64/httpd/modules`.

**Comment by otherjoel** [comment]
> The README directs users to replace the entire Apache configuration folder with the contents of this repo, and set the ServerRoot directive to this same folder. But there is no conf/ folder in this repo 

There is a similar problem with the `modules` subfolder, which exists in the “stock” Apache2 config folder that comes with most distros, but not in this repo which is intended to replace the stock folder:

https://github.com/h5bp/server-configs-apache/blob/9cb2763d7f5e3fce984bfdea903e9df61cdf4bcd/httpd.conf#L14-L19

In CentOS 8, for example, the folder containing Apache configs includes a `modules` that is a symlink to `/usr/lib64/httpd/modules`.

**Comment by LeoColomb** [comment]
Thanks a lot for opening this issue @otherjoel.

For the context:
* The current README has been changed recently to follow recent server-level configuration addition. It is not yet released and will comes with a major release.
* Matching with Docker httpd image is a goal. It seems the paths are not the same depending of the OS, which makes things harder.

---

> The README directs users to replace the entire Apache configuration folder

That is a good catch, do we agree that if we only overwrite existing files but not delete all others, the configuration will work fine?

**Comment by otherjoel** [comment]
> That is a good catch, do we agree that if we only overwrite existing files but not delete all others, the configuration will work fine?

This would solve #219, and would solve this issue on some distributions (i.e., as long as `mime.types` is located where this repo’s `httpd.conf` says it is) and leave it broken on others.

But in general, I agree: updating the documentation would be one good solution in my view. The conf files may not be a total drop-in replacement, but as long as one can follow all the directions and not be left hanging with inexplicable errors, it should be good. 

In that vein, consider adding `TypesConfig` as one of the directives the user should look out for and possibly edit?

**Comment by LeoColomb** [comment]
> But in general, I agree: updating the documentation would be one good solution in my view.

Cool, I'll update soon.


> In that vein, consider adding `TypesConfig` as one of the directives the user should look out for and possibly edit?

I'm not sure to understand, sorry, what do you mean?

**Comment by otherjoel** [comment]
> I'm not sure to understand, sorry, what do you mean?

I was referring to the bulleted list under [“Check `httpd.conf` settings”](https://github.com/h5bp/server-configs-apache/blob/9cb2763d7f5e3fce984bfdea903e9df61cdf4bcd/README.md#check-httpdconf-settings) in the current version of `README`. Something like the following could be added:

> * `TypesConfig`  
(ensure that the path for the `mime.types` file is valid; some distros locate it at `/etc/mime.types`)

**Comment by LeoColomb** [comment]
Oh I see! Yes, good suggestion, thanks 👍

**Comment by LeoColomb** [comment]
@otherjoel I've pushed https://github.com/h5bp/server-configs-apache/commit/6862ac17ed60042c4eb47b56c8da055e99ad4dac in order to address this erroneous guide.

As it's surely perfectible, let me know if you have any other suggestion. 🙂
