### ISSUE TITLE
Non-existent `modules` subfolder

### ISSUE THREAD

**Issue by otherjoel** [h5bp/server-configs-apache#219]
This is similar to #218:

> The `README` directs users to replace the entire Apache configuration folder with the contents of this repo, and set the ServerRoot directive to this same folder. But there is no `conf/` folder in this repo 

There is a similar problem with the `modules` subfolder, which exists in the “stock” Apache2 config folder that comes with most distros, but not in this repo which is intended to replace the stock folder:

https://github.com/h5bp/server-configs-apache/blob/9cb2763d7f5e3fce984bfdea903e9df61cdf4bcd/httpd.conf#L14-L19

In CentOS 8, for example, the folder containing Apache configs includes a `modules` that is a symlink to `/usr/lib64/httpd/modules`.

**Comment by LeoColomb** [comment]
Thanks for opening this issue. As it's very similar to #218, let's keep the discussion on one issue only.
