### ISSUE TITLE
`Expect-CT` header

### ISSUE THREAD

**Issue by LeoColomb** [h5bp/server-configs-apache#222]
Support Certificate Transparency header.

---

* Paper: https://httpwg.org/http-extensions/expect-ct.html
* MDN: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Expect-CT
* CanIUse: https://caniuse.com/#feat=mdn-http_headers_expect-ct

**Comment by Malvoz** [comment]
FYI the MDN docs now has a note:

> The `Expect-CT` will likely become obsolete in June 2021. Since May 2018 new certificates are expected to support SCTs by default. Certificates before March 2018 were allowed to have a lifetime of 39 months, those will all be expired in June 2021.

Assuming that is correct, perhaps there's little value in adding this header?

**Comment by LeoColomb** [comment]
@Malvoz Good catch, thanks for that! 👍  
What do you suggest? We close issue/pr as almost obsolete?

**Comment by Malvoz** [comment]
Yes, let's close this. 👍
