### ISSUE TITLE
Forcing HTTPS

### ISSUE THREAD

**Issue by ethanbeyer** [h5bp/server-configs-apache#232]
I have run an Apache server for long time with the impression that I needed ports 80 and 443 available for a site, with a redirect from 80 (non-https) to 443.

I don't see a way in the documentation for the usage of this library to ensure that non-https traffic is redirected to https. Do I have a misunderstanding for this?

**Comment by LeoColomb** [comment]
Do you mean exactly what this file explains? 😉 

https://github.com/h5bp/server-configs-apache/blob/d714db671adf4f5463f4e3201ac6ea27ce32d4ff/h5bp/rewrites/rewrite_http_to_https.conf#L1-L24

**Comment by ethanbeyer** [comment]
I feel pretty stupid - did not see that!

Thank you...
