### ISSUE TITLE
No apache2 in /usr/local

### ISSUE THREAD

**Issue by ethanbeyer** [h5bp/server-configs-apache#233]
I'm working on using this repository to bootstrap the install scripts on several servers.

I keep getting to [this place](https://github.com/h5bp/server-configs-apache#directly) in the README, and scratch my head.

My `/usr/local/` directory has no `apache2` directory.

No matter, I thought. I decided to clone this repository into my home folder and then symlink it to `/usr/local/apache2`. That part works great - but when I try to then load the `httpd.conf`, an error arises from line 16, `LoadModule mpm_event_module modules/mod_mpm_event.so`.

I think this is due to the fact that there wasn't already an `apache2` folder in `/usr/local` to merge modules with. But I most definitely could be off track.

I know this isn't a support forum, but I am trying my best to understand how to set this up correctly.

**Comment by ethanbeyer** [comment]
I suppose it never helps to post issues without the stack of things I've done.

1. New AWS Lightsail instance running Ubuntu 18.04
2. Ran the following commands to install necessary tools for a LAMP stack:

```sh
sudo add-apt-repository ppa:ondrej/php
sudo add-apt-repository ppa:ondrej/apache2
sudo add-apt-repository ppa:certbot/certbot
sudo apt update
sudo apt upgrade
sudo apt full-upgrade
sudo apt autoremove
sudo apt install \
  apache2 \
  certbot \
  curl \
  mysql-client \
  mysql-server \
  openssh-server \
  php7.4 \
  php7.4-bcmath \
  php7.4-bz2 \
  php7.4-cli \
  php7.4-common \
  php7.4-curl \
  php7.4-fpm \
  php7.4-gd \
  php7.4-gettext \
  php7.4-intl \
  php7.4-mbstring \
  php7.4-mysql \
  php7.4-readline \
  php7.4-xml \
  php7.4-zip \
  python-certbot-apache \
  screen \
  software-properties-common \
  unzip \
  wget \
  zip
```

It is at this point that I was going to try to use this repo's configs - but there is no `/usr/local/apache2` directory to backup or write to.

**Comment by LeoColomb** [comment]
Thanks for opening this issue @ethanbeyer.

> there is no `/usr/local/apache2` directory

This is the default directory, but Apache httpd configuration directory can be different, especially if the version used is not the official one. See [official httpd documentation](https://httpd.apache.org/docs/current/getting-started.html#configuration).

You may find yours in `/etc/apache2/` for example, or something similar.
Please refer to the documentation for the repository in use.

**Comment by ethanbeyer** [comment]
Thank you @LeoColomb - apologies for raising this as an issue with the repository.

I am still trying to figure out how to integrate these configs with the Ubuntu defaults, which as you said, are located in `/etc/apache2`.

Is there anywhere that explains how to use this repository with Debian/Ubuntu? That OS' configuration requires the use of `conf-enabled`, so I am not sure how to use this repository as the basis for the server's configuration.

Unless, thinking as I am typing here, I need to disable all of Apache's default configs and enable all of these configs in `conf-enabled`?

I just don't know.

**Comment by LeoColomb** [comment]
> how to use this repository with Debian/Ubuntu

We aim to keep this repository generic as much as possible.

> That OS' configuration requires the use of `conf-enabled`,

`conf-enabled` is never required, it's only suggested to be used in line with `a2ensite`.
This repository suggest using `vhosts` folder, but the goal is the same and it won't affect configuration usage or performance, only `a2ensite` usage.

The in-use directory must be reflected in the main `httpd.conf` file.

https://github.com/h5bp/server-configs-apache/blob/939269a3a4e1ac205719d717bb402a371e0522ad/httpd.conf#L145-L148

If you need more help on how to configure Apache httpd, I suggest reaching your host's support.
