### ISSUE TITLE
Question about the license

### ISSUE THREAD

**Issue by julianpoemp** [h5bp/server-configs-apache#236]
Hi,
I'm thinking about an integration of your .htaccess code to a htaccess generation tool that I'm currently developing. The tool is a web-application that helps Angular developers to create an optimal .htaccess file for their web-applications. The .htaccess file is generated related to the answers from the interview. The project is open-source, non-commercial and under MIT License, too.

May I integrate your .htaccess file? I would like to use your .htaccess code with comments. Of course I would reference this repository and I would give credits.

**Comment by LeoColomb** [comment]
Thanks for your question @julianpoemp.

Sure. Check out the following guide to get an overview of how you can use MIT-licensed code: https://choosealicense.com/licenses/mit/

**Comment by julianpoemp** [comment]
@LeoColomb thank you very much. I know the MIT license, but I liked to ask to make sure, it's okay because I respect your work :)
