### ISSUE TITLE
apache2 rename to apachectlone

### ISSUE THREAD

**Issue by Srinivasa381224** [h5bp/server-configs-apache#261]
Hi this is srinivasa am installed apache2 in ubuntu using
sudo apt install apache2
now i can able to start service, 
sudo service apache2 start
But my problem is i need to start a service like apachectlone means
sudo service apachectlone start
i need to use this command to start the service But i dont know how can i change this please help me for this which are the places i need to change details

**Comment by LeoColomb** [comment]
Thanks for opening this ticket @Srinivasa381224.
That said you are referring to software not managed by this repository, and where we can't provide any support.
Please refer to your host/software provider.
