### ISSUE TITLE
Release number vs. git describe

### ISSUE THREAD

**Issue by tomkyle** [h5bp/server-configs-apache#263]
Sorry if this is a dumb question – so H5BP is currently tagged 4.10, but `git describe` on a freshly cloned repo gives me `2.1.0-366-g3c7db53`. How come?

**Comment by LeoColomb** [comment]
Thanks for your question, @tomkyle.
Are you sure the clone is really fresh? `g3c7db53` commit does not exist, and is not the last commit anyway.

**Comment by LeoColomb** [comment]
> By default (without --all or --tags) git describe only shows annotated tags. For more information about creating annotated tags see the -a and -s options to git-tag[1].

https://git-scm.com/docs/git-describe

**Comment by tomkyle** [comment]
Thx for your reply! In fact, `get describe --tags` outputs 4.1.0... Funny with `g3c7db53` ...

```bash
me@computer:~ $ git clone https://github.com/h5bp/server-configs-apache.git fresh
Klone nach 'fresh' ...
remote: Enumerating objects: 75, done.
remote: Counting objects: 100% (75/75), done.
remote: Compressing objects: 100% (63/63), done.
remote: Total 3281 (delta 41), reused 20 (delta 11), pack-reused 3206
Empfange Objekte: 100% (3281/3281), 1.13 MiB | 2.66 MiB/s, fertig.
Löse Unterschiede auf: 100% (1811/1811), fertig.
me@computer:~ $ cd fresh
me@computer:~/fresh ‹master›$ git fetch
me@computer:~/fresh ‹master›$ git pull
Bereits aktuell.
me@computer:~/fresh ‹master›$ git describe
2.1.0-366-g3c7db53
me@computer:~/fresh ‹master›$ git describe --tags
4.1.0
me@computer:~/fresh ‹master›$
```
