### ISSUE TITLE
SSL Session Cache can't be in virtualhost

### ISSUE THREAD

**Issue by ObjectifMars** [h5bp/server-configs-apache#264]
The following problem is into the last release 4.1.0 and into the master branche.

The configuration for SSL Session cache is put into the file [`h5bp\ssl\ssl_engine.conf`](https://github.com/h5bp/server-configs-apache/blob/3c7db53404c23ba705ff56dda7096c82cc409e8c/h5bp/ssl/ssl_engine.conf#L29), this configuration is put by default into the template for a SSL VirtualHost `vhosts\templates\example.com.conf` and `vhosts\.000-default.conf`.

https://github.com/h5bp/server-configs-apache/blob/3c7db53404c23ba705ff56dda7096c82cc409e8c/h5bp/ssl/ssl_engine.conf#L29-L32

When installing the module mod_socache_shmcb.so into httpd.conf on a Apache container ([httpd:2.4.46](https://hub.docker.com/_/httpd)), I have this error message and the server stop :
```apache
AH00526: Syntax error on line 30 of /usr/local/apache2/h5bp/ssl/ssl_engine.conf:
SSLSessionCache cannot occur within <VirtualHost> section
```

I think the solution is : 
1. ever the ssl_engine.conf need to be include directly into `httpd.conf` or the directives need to be splited into 2 files one to be included into httpd.conf (with the cache SSL configuration), the other with the remaining lines into the vhosts. I think the first option is enough : it's the minimal configuration of the SSL module so it can be included into `httpd.conf`.
2. Add into `httpd.conf` : `LoadModule socache_shmcb_module modules/mod_socache_shmcb.so`

**Comment by LeoColomb** [comment]
Thanks for opening this issue @ObjectifMars!
That's a really good catch, I'm curious why it hasn't been spotted before.

Anyway, I'd say the best option is to extract block checking presence of shmcb mod into `httpd.conf`.

Would you like to open a pull request?

**Comment by ObjectifMars** [comment]
I will try to create a pull request, it will be a first simple enough.
