### ISSUE TITLE
Add `Permissions-Policy` directive to control FLoC

### ISSUE THREAD

**Issue by doktorbro** [h5bp/server-configs-apache#266]
google’s [floc]( https://blog.google/products/ads-commerce/2021-01-privacy-sandbox/) is coming. it’s time to react.
 
* eff said: [google’s floc is a terrible idea](https://www.eff.org/deeplinks/2021/03/googles-floc-terrible-idea)
* brave said: [why brave disables floc](https://brave.com/why-brave-disables-floc/)
* wordpress said: [treat floc like a security concern](https://make.wordpress.org/core/2021/04/18/proposal-treat-floc-as-a-security-concern/)

the apache config to opt out the floc is:

```apache
<IfModule mod_headers.c>
  Header always set Permissions-Policy "interest-cohort=()"
</IfModule>

**Comment by LeoColomb** [comment]
Thanks a lot for opening this issue @doktorbro!

While I'm personally in favor of blocking FLoC, I'm not sure about its addition into H5BP.
* This is quite political for now, and it's probably better to wait a bit.
* Especially regarding current web ecosystem reaction, it might be useless in few months (FLoC is "only" a experiement).
* This addition won't be enabled by default, reducing its value in short-term and its coverage.
* And finally there is already a issue regarding Permissions-Policy header: #179.

**Comment by doktorbro** [comment]
@LeoColomb if it’s better to wait then i will.

**Comment by LeoColomb** [comment]
I'm gonna to close this one in favor of #179
