### ISSUE TITLE
Increase cache for images and fonts

### ISSUE THREAD

**Issue by jamieburchell** [h5bp/server-configs-apache#289]
Google Lighthouse seems to complain that assets with a cache expiry of 30 days should be set with longer expiry times. I believe the thinking is if it's OK to cache something for 30, it's probably OK to cache something for a year. Certainly, when I changed my own config to expiry images and fonts from 30 days to 1 year, Lighthouse was happy.

**Comment by jamieburchell** [comment]
@LeoColomb [This page](https://web.dev/uses-long-cache-ttl/) is as close as I can get to that.

The screenshot shows assets flagged with a 30 day TTL under the heading "Serve assets with an efficient cache policy". Further down the same page, is an example for setting the TTL for 1 year and the recommendation "When possible, cache immutable static assets for a long time, such as a year or longer.".

In my own testing, setting the TTL to 1 year (and no other changes) stops the assets from getting flagged under this category.

Also see [this issue](https://github.com/GoogleChrome/lighthouse/issues/6627) and specifically, [this comment](https://github.com/GoogleChrome/lighthouse/issues/6627#issuecomment-440858210)

**Comment by LeoColomb** [comment]
I would not, the granularity is still required to avoid to many false positive.

**Comment by jamieburchell** [comment]
If something can be cached for one month, why not cache it for a year, as suggested by Google?

**Comment by LeoColomb** [comment]
Yes, for sure, for image and other media. Not for everything though.

**Comment by jamieburchell** [comment]
OK, so I should change all of the individual entries for media files and web fonts from "1 month" to "1 year" in this file https://github.com/h5bp/server-configs-apache/blob/main/h5bp/web_performance/cache_expiration.conf. Do I need to build the dist file too? Should the same be done for nginx configs?

**Comment by LeoColomb** [comment]
Exactly, that should make the trick! 🙂
Don't build anything, it's automatic.
And of course, you're more than welcome to do the same on Nginx configs! (but let's start with Apache first)

**Comment by LeoColomb** [comment]
> If something can be cached for one month, why not cache it for a year, as suggested by Google?

After a second thought, it might actually be a good idea.
Thing is I can find any public recommendation, except these few lines from Google... It is quite difficult to guess if raising this TTL can cause any trouble.

**Comment by jamieburchell** [comment]
Why not just stick with the PR then, which only caches images and fonts for 1 year instead of 30 days
