### ISSUE TITLE
Pre-compressed rewrite directives without `mod_rewrite` check

### ISSUE THREAD

**Issue by DanielRuf** [h5bp/server-configs-apache#291]
It looks like there is `mod_headers` used but it should be probably `mod_rewrite`:

https://github.com/h5bp/server-configs-apache/blob/2471dd8e1de003a5d3488480468e85c0cdb3647a/h5bp/web_performance/pre-compressed_content_brotli.conf#L20

https://github.com/h5bp/server-configs-apache/blob/2471dd8e1de003a5d3488480468e85c0cdb3647a/h5bp/web_performance/pre-compressed_content_gzip.conf#L19

Original issue / report: https://github.com/h5bp/html5-boilerplate/issues/2633

**Comment by DanielRuf** [comment]
Very confusing that the Apache docs do not include the mod_rewrite ifmodule checks there.

I guess something like this makes more sense?

```
<IfModule mod_rewrite.c>
...
<IfModule mod_headers.c>
    # Force proxies to cache brotlied and non-brotlied files separately
    Header append Vary Accept-Encoding
    </IfModule>
...
</IfModule>
```

**Comment by LeoColomb** [comment]
Thanks for opening this case, @DanielRuf.
Indeed, looks like an additional check for `mod_rewrite` might be relevant.
Having a failure here is highly unlikely, but for the sake of strictness why not.

**Comment by bulan575758** [comment]
mungkin mod bisa dicek [http://193.70.117.226/](http://193.70.117.226/)

**Comment by Davvy42** [comment]
Thanks for the update have you heard of globetradefx company
