### ISSUE TITLE
Correctly resolve path of build script

### ISSUE THREAD

**Issue by tomkyle** [h5bp/server-configs-apache#294]
The **bin/build.sh** script does (at least on MacOS) not correctly resolve it's file path when the build.sh script has been symlinked: Variable "$0" in build.sh will not contain the 'real' file name but the symlinks path rather, e.g. `/Users/me/bin/build-htaccess` instead of expetcted `/Users/me/server-configs-apache/bin/build.sh`

The following **$repo_root** determination is then based on false assumptions. Adding `realpath` could fix this:

```bash
# repo_root=$(dirname "$(dirname "$0")")
repo_root=$(dirname "$(dirname "$(realpath "$0")")")
```

What do you think?

**Comment by LeoColomb** [comment]
Thanks for the report @tomkyle!
Well as soon as it still resolves with other Linux bash, I don't have anything against 🙂
