### ISSUE TITLE
Feature request: video/mov in .htaccess?

### ISSUE THREAD

**Issue by nielsjakob** [h5bp/server-configs-apache#296]
Wondering why there's no mention of .mov in https://github.com/h5bp/html5-boilerplate/blob/main/dist/.htaccess.

Is this missing on purpose? Otherwise it would be great to add it :)

**Comment by LeoColomb** [comment]
Thanks for opening this issue @nielsjakob.
I would prefer to ask the opposite: why should `mov` files be mentioned here?
It is not missing on purpose, but should be added only on purpose.

**Comment by nielsjakob** [comment]
Okay I could have been a bit more specific about where I feel mov is missing:

<IfModule mod_mime.c>
    // ...
    AddType video/mp4 f4v f4p m4v mp4
    // ...
</IfModule>

and

<IfModule mod_expires.c>
    // ...
    ExpiresByType video/mp4 "access plus 1 month"
    // ...
</IfModule>

I believe the idea is that when a user visits the page a second time, the video is still in their cache and doesn't have to be downloaded again.

**Comment by LeoColomb** [comment]
My question was more regarding the use case for `.mov` files.
Is this specific file type something you use on the web, and then expect to be managed by a web server?

**Comment by nielsjakob** [comment]
Okay I looked into it and realised that I better user .mp4 and .webm.

Still wonder if it should be included, since it won't affect people not using .mov and it will help those who do use it.

On the other hand, if it was included I wouldn't have researched this further and would've continued to use .move :D
