### ISSUE TITLE
`DirectoryIndex` comment if pre-compressed content is enabled

### ISSUE THREAD

**Issue by vatonbero** [h5bp/server-configs-apache#309]
Hi there,

I have re-visited pre-compressed file serving examples from h5bp [.htaccess](https://github.com/h5bp/server-configs-apache/blob/main/dist/.htaccess) and they work like a charm.

Since this was my first time enabling this, I wanted to go through multiple scenarios and I have noticed if pre-compressed archive is your only way of serving pages then you might end up in case where Apache is not serving that file because it will probably expect  change from `index.[html|php]` instead of `index.[br|gz]` or anything else.

Would it be worth thinking about adding comment about this in the h5bp htaccess file? Something among these lines:

Brotli
```apache
[...]
<IfModule mod_rewrite.c>
  # If you enabled brotli pre-compressed file serving, it would be worthwhile making brotli file default index
  DirectoryIndex  index.br index.html
[...]
```

Gzip
```apache
[...]
<IfModule mod_rewrite.c>
  # If you enabled Gzip pre-compressed file serving, it would be worthwhile making Gzip file default index
  DirectoryIndex  index.gz index.html
[...]
```

Thank you.

**Comment by LeoColomb** [comment]
Thanks for opening this issue @vatonbero, quite interesting.
Adding a comment to explain the case is a nice idea, indeed.
Would you like to submit a pull request?

One note though: `DirectoryIndex` attribute value is application specific when this project aims to be app agnostic. The comment will most probably "just" a notice than a complete example of what to do.

**Comment by vatonbero** [comment]
@LeoColomb I can make something and create PR, why not.

> One note though: `DirectoryIndex` attribute value is application specific when this project aims to be app agnostic. The comment will most probably "just" a notice than a complete example of what to do.

I was referring to Apache [`DiectoryIndex`](https://httpd.apache.org/docs/2.4/mod/mod_dir.html#directoryindex) in Brotli/Gzip context of htaccess and implementation so it should be web application agnostic. Care to share what is missing and how can I improve this idea?

**Comment by LeoColomb** [comment]
> I was referring to Apache [`DirectoryIndex`](https://httpd.apache.org/docs/2.4/mod/mod_dir.html#directoryindex)

Yes, but as mentioned, I'm referring to the value you provide to this directive. `index.gz index.html` is not application agnostic. 

> Care to share what is missing and how can I improve this idea?

Nothing is missing, the initial comment looks perfect, `DirectoryIndex` aside. 😊

**Comment by vatonbero** [comment]
Thank you for your answers.

I have created PR https://github.com/h5bp/server-configs-apache/pull/311

English is not my primary language so maybe some word tumbling might be required :smile:
