### ISSUE TITLE
Question: mpm_winnt_module

### ISSUE THREAD

**Issue by thpoiani** [h5bp/server-configs-apache#312]
Hello Community.
I am setting up an Apache HTTP Server in a Windows Server following this repository as base.
I got a failure in the `mod_mpm_event` because Windows use [`mpm_winnt`](https://httpd.apache.org/docs/2.4/mod/mpm_winnt.html). Example:

```apache
<IfModule mpm_winnt_module>
    ThreadsPerChild      150
    MaxRequestsPerChild    0
</IfModule>
```

Would you guys suggest any specific configuration for this module, or should I leave it disabled?

**Comment by LeoColomb** [comment]
Thanks for opening this issue @thpoiani.
That said I'm not sure to understand the context here:
* What is the error?
* Is it directly related to H5BP configuration template?

**Comment by LeoColomb** [comment]
Thanks for your reply @thpoiani.
I'm afraid this is going outside of project scope.
Don't hesitate to gather community help on dedicated forums.
