### ISSUE TITLE
Remove `image/avif-sequence` MIME type

### ISSUE THREAD

**Issue by mathiasbynens** [h5bp/server-configs-apache#313]
Per https://github.com/AOMediaCodec/av1-avif/pull/86

We should probably keep the `avifs` extension and just map it to `image/avif` instead.

**Comment by laukstein** [comment]
.avifs has been removed from spec https://github.com/AOMediaCodec/av1-avif/pull/86/commits/bcb318f5bfec1a809f852089757765dd8e4d5fd6

**Comment by LeoColomb** [comment]
That means this line should basically be dropped, right?
https://github.com/h5bp/server-configs-apache/blob/7eaa1b85da73ec6be2dbc924d1ef22f7848e0b05/h5bp/media_types/media_types.conf#L43

**Comment by mathiasbynens** [comment]
@LeoColomb There’s two parts: 1) drop that line 2) add `avifs` to the `image/avif` line.

**Comment by LeoColomb** [comment]
@mathiasbynens This is where I get confused: as mentioned by @laukstein, the `.avifs` filetype [seems to has been removed as well](https://github.com/AOMediaCodec/av1-avif/commit/bcb318f5bfec1a809f852089757765dd8e4d5fd6). Right?

**Comment by mathiasbynens** [comment]
> @mathiasbynens This is where I get confused: as mentioned by @laukstein, the `.avifs` filetype [seems to has been removed as well](https://github.com/AOMediaCodec/av1-avif/commit/bcb318f5bfec1a809f852089757765dd8e4d5fd6). Right?

I mentioned that too — the commit @laukstein linked to is what resolved the issue I pointed to.

The reason we probably still wanna have `avifs` supported (as `image/avif`) is because of backwards compatibility: people are already using it, and outright removing `.avifs` altogether would needlessly break those use cases.

**Comment by LeoColomb** [comment]
Make sense.
See #316
