### ISSUE TITLE
Variable evaluation in build script

### ISSUE THREAD

**Issue by nlemoine** [h5bp/server-configs-apache#317]
Hey!

I'm currently facing an issue with the build script. I'm trying to generate a custom htaccess file while including a custom partial in it. Here's a basic example:

```apache
title   "cross-origin"
enable  "h5bp/cross-origin/images.conf"
enable  "h5bp/cross-origin/web_fonts.conf"
enable "~/my/custom/path/custom-conf.conf"
```

Problem is `~` is never evaluated, neither `$HOME`. 
https://github.com/h5bp/server-configs-apache/blob/06df209e2e24832124e09f4f88d4bf4cf1cf4d38/bin/build.sh#L52

I suck in bash, do you think it would possible to enable this?

**Comment by LeoColomb** [comment]
Thanks for opening this issue @nlemoine.

Environment variables like `$HOME` are used and expanded if well registered in bash env. Seeing your pull request #318 I believe this is working properly, right?
On the other hand, `~` is a custom alias, which I would not recommend for filename and folder descriptions. It is too weak.
I would highly recommend to use `$HOME` instead.

In that extent, I'm going to close your PR #318.

**Comment by nlemoine** [comment]
Thanks for the prompt reply @LeoColomb!

The problem is that `$HOME` is not evaluated either. I end up with something like:
```
[✖] .htaccess partial '/var/ww/html/h5bp/$HOME/some/path/to/custom-conf.conf' does not exist.
```

I tried:
```
enable "${HOME}/path/to/custom-conf.conf"
enable "$HOME/path/to/custom-conf.conf"
```

With or without quotes.
