### ISSUE TITLE
Add build parameter to generate `.htaccess` without comments

### ISSUE THREAD

**Issue by pauloxnet** [h5bp/server-configs-apache#329]
Currently, two-thirds of the file generated by the build command is comments. It might be useful to be able to generate a file without comments to be lighter and faster to read, leaving the option to continue generating the version with comments. I imagine an attribute to be passed to the script might be fine for this purpose.

**Comment by LeoColomb** [comment]
Thanks for opening this issue @pauloxnet.
While this is a great idea, the implementation in the script will be quite challenging, if even reasonably possible.
The comments are already written in the files from which the script is generating the `.htaccess`, and there isn't any content processing so far.

If you want to remove all the comments in the generated file, I'd recommend running the following simple yet efficient command (might not be the most optimized, though). 
```shell
sed -i '/^#/d' .htaccess
```

**Comment by pauloxnet** [comment]
> Thanks for opening this issue @pauloxnet.
> While this is a great idea, the implementation in the script will be quite challenging, if even reasonably possible.
> The comments are already written in the files from which the script is generating the `.htaccess`, and there isn't any content processing so far.
> 
> If you want to remove all the comments in the generated file, I'd recommend running the following simple yet efficient command (might not be the most optimized, though). 
> ```shell
> sed -i '/^#/d' .htaccess
> ```

Thanks for your answer 😃
