### ISSUE TITLE
ServerTokens Prod missing, now full server details in response header by default

### ISSUE THREAD

**Issue by jamieburchell** [h5bp/server-configs-apache#330]
It seems that `ServerTokens Prod` has been removed which is now causing the full Apache and OpenSSL version information to be output in the response headers.

**Comment by LeoColomb** [comment]
Thanks for opening this issue, @jamieburchell.
That being said, the `ServerTokens` directive is still present and actively recommended in here:

https://github.com/h5bp/server-configs-apache/blob/14d8af4ac96a0918713f63e370f894b4305bb025/httpd.conf#L97

The older issue is probably relevant to your question as well: https://github.com/h5bp/server-configs-apache/issues/153

**Comment by jamieburchell** [comment]
@LeoColomb I took the dist file, it's missing from there but was there previously. That's what I base my configs from.
