### ISSUE TITLE
Missing `<IfModule mod_authz_core.c>` block

### ISSUE THREAD

**Issue by jamieburchell** [h5bp/server-configs-apache#331]
Should this be wrapped in the conditional check for the module, like in other places?

https://github.com/h5bp/server-configs-apache/blob/14d8af4ac96a0918713f63e370f894b4305bb025/httpd.conf#L128

**Comment by LeoColomb** [comment]
Thanks for opening this issue, @jamieburchell.
Indeed, this is a good catch, it should be surrounded by the appropriate `<IfModule>`.
Would you like to submit a pull request?
