### ISSUE TITLE
Add `<IfModule http2_module>` for h2 protocol support

### ISSUE THREAD

**Issue by jamieburchell** [h5bp/server-configs-apache#334]
Would you consider wrapping [this Protocols line](https://github.com/h5bp/server-configs-apache/blob/e1733a275b375c51da264ef3b3e882aec8aa09bf/httpd.conf#L109) in a conditional block?

```
<IfModule http2_module>
    Protocols h2 http/1.1 
</IfModule>
```

This is useful for two reasons: Only declare protocol support for h2 when the module is loaded and also support Apache <2.4.17 where the `Protocols` declaration is not available (note your README states support for Apache 2.4.10+).

**Comment by bchr** [comment]
Just a few thoughts:

From https://httpd.apache.org/docs/2.4/howto/http2.html

> The protocols you configure are not checked for correctness or spelling. You can mention protocols that do not exist, so there is no need to guard `Protocols` with any `<IfModule>` checks.

Also, I guess it could be discussed whether or not to add the `h2c` protocol as well?

The server can be configured to allow the client to choose what it prefers via `ProtocolsHonorOrder`.

Maybe a seperate issue/discussion?

**Comment by jamieburchell** [comment]
> Just a few thoughts:
> 
> From https://httpd.apache.org/docs/2.4/howto/http2.html
> 
> > The protocols you configure are not checked for correctness or spelling. You can mention protocols that do not exist, so there is no need to guard `Protocols` with any `<IfModule>` checks.
> 
> Also, I guess it could be discussed whether or not to add the `h2c` protocol as well?
> 
> The server can be configured to allow the client to choose what it prefers via `ProtocolsHonorOrder`.
> 
> Maybe a seperate issue/discussion?

Apache will fail to start if it finds the `Protocols` declaration at all in <2.4.17 (your supported version is less than this).

**Comment by bchr** [comment]
I see.

It could be solved by `<IfVersion >= 2.4.17>`.

Apache 2.4.10 was released in 2014. In my opinion it's a shame if we can't benefit from all the development that's happened in Apache since then. A lot of new features could probably go into this project if the maintainers would go down that route :-)

**Comment by LeoColomb** [comment]
Thanks for opening this issue, @jamieburchell.
I believe it is safe to bump H5BP requirement to 2.4.17.

**Comment by jamieburchell** [comment]
I have CentOS 7 VMs which are still supported, with Apache 2.4.6 which is still receiving backported fixes. For me the check is useful so that I can continue using this script even on older versions.

**Comment by LeoColomb** [comment]
While I understand your position, I'm going to reject it:
* `<IfVersion>` could be handy to use indeed, but require another module to be loaded (`mod_version`), which implies:
  * Add the module at loading time
  * Make sure the module is available before using the block (with a `<IfModule>` for `mod_http2`)
  * Take the risk to disable http2 usage for server without `mod_version` even if `mod_http2` is available.
* Segregating versions inevitably makes the maintenance harder, as the configuration behavior could change depending on the version. We don't have the bandwidth to do that.

CentOS 7 is in its last year(-ish) of support, and Apache http server 2.4.6 is very very old, I'm not sure enabling their usage with H5BP is something I'd like to do.

I hope you see my point! 😊

**Comment by bchr** [comment]
Solution:

```
+ <IfModule mod_http2.c>
    Protocols h2 http/1.1
+ </IfModule>
```
😃

**Comment by jamieburchell** [comment]
> Solution:
> 
> ```
> + <IfModule mod_http2.c>
>     Protocols h2 http/1.1
> + </IfModule>
> ```
> 
> 😃
> 
> By the way in Debian and Ubuntu, the version_module `(mod_version.c)` is a static module and therefore compiled into Apache. It cannot be en/dismodded. Those can be seen by `apachectl -M | grep static`.

This is what I proposed originally and what I ended up adding to my config.

**Comment by bchr** [comment]
I created a pull request. Let's see if it get's merged.
