### ISSUE TITLE
Error with `Permissions-Policy` header: Unrecognized feature: `'document-domain'`

### ISSUE THREAD

**Issue by bs-thomas** [h5bp/server-configs-apache#356]
For some reason, when I uncomment to enable the Permissions Policy header.

```apache
<IfModule mod_headers.c>
    Header always set Permissions-Policy "accelerometer=(),autoplay=(),camera=(),display-capture=(),document-domain=(),encrypted-media=(),fullscreen=(),geolocation=(),gyroscope=(),magnetometer=(),microphone=(),midi=(),payment=(),picture-in-picture=(),publickey-credentials-get=(),screen-wake-lock=(),sync-xhr=(self),usb=(),web-share=(),xr-spatial-tracking=()" "expr=%{CONTENT_TYPE} =~ m#text\/(html|javascript)|application\/pdf|xml#i"
</IfModule>
```

this is givinhg me an error on Chrome Version 117.0.5938.92 (Official Build) (64-bit):

Error with Permissions-Policy header: Unrecognized feature: 'document-domain'.

I also tried various things according to this doc:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Permissions-Policy#syntax

Such as 

document-domain=(\"self\")

But still the same.

Would anyone happen to know what is happening, or shed me some light?  Is it something Chrome is just not yet supported?  Or is there an issue with the syntax?

Your help is appreciated!!
Thank you!

**Comment by LeoColomb** [comment]
Thanks for opening this issue @bs-thomas.
Indeed, [according to MDN's support table](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Permissions-Policy/document-domain#browser_compatibility), this feature is not yet supported by any browser.
Its presence here in the list is probably a bit early. It is both safe to ignore the warning and remove it from the list for the moment.
