### ISSUE TITLE
Add `ExpiresByType` for `audio/mp4` with `"access plus 1 year"`

### ISSUE THREAD

**Issue by creopard** [h5bp/server-configs-apache#360]
If you are serving m4a files on a website, it can be helpful to stretch the cache expiration for this type.

The current `.htaccess` file only includes:
`ExpiresByType video/mp4                             "access plus 1 year"`

However, Google's Lighthouse will complain about **m4a** files with "_Serve static assets with an efficient cache policy_", since the default `ExpiresDefault` of 1 month is too short for this type.

Adding cache expiration for "audio/mp4" like:
`ExpiresByType audio/mp4                             "access plus 1 year"`

will fix that, since the mime type of "audio/mp4" is already included in the "Media types" section:

```apacheconf
# Media files
AddType audio/mp4                                   f4a f4b m4a
```

**Comment by LeoColomb** [comment]
Thanks for opening this issue, @creopard.
Sounds good. Would you like to open a pull request?

**Comment by creopard** [comment]
@LeoColomb it seems this setting has been replaced in the current repo [(h5bp/web_performance/cache_expiration.conf)](https://github.com/h5bp/server-configs-apache/commit/dbc38dd975c11c851ced37fbf66e20f4a1e6f989#diff-6997bf9ed97ab7041840ea9d050b18d3599e39f6dcb5ce2eed20983bbd8aad39R61) by:
```
    # Generic: Medias
    # ExpiresByType audio/*                             "access plus 1 year" # default
    # ExpiresByType video/*                             "access plus 1 year" # default
```
So I guess that's optional now?
Will the build script replace the asterisk (*) in these lines with the specific file extensions like "mp4"?

**Comment by LeoColomb** [comment]
Oh yes, indeed, it is already covered.
There is no build script for this part, the `*` can be used to "glob" all audio/video prefixed MIME-types.
And that part is commented out as it is falling back in the default case perfectly.
https://github.com/h5bp/server-configs-apache/blob/c616cf5e4a27f72321680097b4b3ee76d6a704c7/h5bp/web_performance/cache_expiration.conf#L18-L19

In short, yes, `audio/mp4` is already been handled correctly.
For this reason, I'm closing the issue, but continue the discussion below if any question.
