### ISSUE TITLE
`mod_cache` and link to trunk version of docs

### ISSUE THREAD

**Issue by nisbet-hubbard** [h5bp/server-configs-apache#374]
Two areas of improvement I’ve seen after reading through your useful snippets:

1. Your caching config focuses on browser caching. Does anyone here have the expertise to offer a recipe for in-memory and disk caching based on the suite of modules around `mod_cache`?
2. References to the Apache docs link to the ‘current’ version, which is something of a misnomer as new work on the 2.4 docs is only being committed to the ‘trunk’ branch.

**Comment by LeoColomb** [comment]
Thanks for opening this issue @nisbet-hubbard.

1. `mod_cache` is only used in specific context with even more specific configuration. As far as I know, it is not possible to offer generic config recommendations. That being said, if it is possible and worth it, a pull request is always welcome.
2. `trunk` branch is the development branch. This means the changes in the documentation are related to non-released code. `current`, on the contrary, is related to the latest published version.

**Comment by LeoColomb** [comment]
> httpd’s general practice to merge new edits in `trunk`

This makes sense, `trunk` being related to development, all the new changes/edits are first visible in `trunk`.
That being said, H5BP aims to target stable releases of upstream software. The current stable of Apache HTTP server is 2.4, which is behind the `current` documentation tag.
It is well-defined in the documentation home page: https://httpd.apache.org/docs/

> safely updated to `/trunk/` to benefit from the improvements in docs.

I'm not sure to understand the benefits of linking to an _eventually_ unstable documentation, to be honest.
