### ISSUE TITLE
Remove only-http from www-normalizing redirects

### ISSUE THREAD

**Issue by AD7six** [h5bp/server-configs-apache#52]
Most users probably aren't using both http and https, but if they are it's possibly confusing/misleading why these redirects only apply to http requests.

So, as mentioned in #49 the `RewriteCond %{HTTPS} =on` conditions should be removed before the next major release.

**Comment by QWp6t** [comment]
I'd suggest commenting it out, not removing it completely.

**Comment by fatbattk** [comment]
Curious as to why `RewriteCond %{HTTPS} =on` was added initially. Were there problems if redirecting secure traffic?

**Comment by QWp6t** [comment]
Yes, oftentimes people get cheap certs that only include one hostname. The idea behind the `RewriteCond` is that you don't want to inadvertently redirect users to a hostname with a self-signed cert.

**Comment by XhmikosR** [comment]
:+1: for this. I had to dig into the code to find out it was skipped on purpose for https.

**Comment by barryvdh** [comment]
Don't most ssl certs support both www. and without www?

Perhaps a note about this should be added, I was wondering about this also.

**Comment by acbilimoria** [comment]
+1

**Comment by UberGruber** [comment]
Hey there! 
So basically what is the suggested practice when is desired a rewrite with HTTPS and WWW? No risks just commenting it out if the certs has both hosts signed right?

**Comment by aubertc** [comment]
@GlassGruber : Cf. https://github.com/h5bp/server-configs-apache/pull/84/files
You can remove (or comment out) both `RewriteCond %{HTTPS} !=on`, actually.
