### ISSUE TITLE
How about remove X-Powered-By

### ISSUE THREAD

**Issue by sheo13666** [h5bp/server-configs-apache#54]
```ApacheConf
<IfModule mod_headers.c>
     Header unset X-Powered-By
</IfModule>
```

**Comment by mathiasbynens** [comment]
FTR, it’s better to do this through `php.ini`, by setting `expose_php = off`. Or do other server-side languages than PHP add this header?

**Comment by sheo13666** [comment]
Many project on php add this header in php script, also many hosting company not give set expose_php = off.

**Comment by mathiasbynens** [comment]
@sheo13666 Don’t get me wrong, I agree we could add this to the settings. I’m just saying we should also add a comment explaining the better alternatives.

**Comment by arthurvr** [comment]
> Don’t get me wrong, I agree we could add this to the settings. I’m just saying we should also add a comment explaining the better alternatives.

:+1:

**Comment by sheo13666** [comment]
@arthurvr yes, some later

**Comment by alrra** [comment]
>  Or do other server-side languages than PHP add this header?

@mathiasbynens PHP isn't even the most popular. Using the data from [HTTP archive](http://httparchive.org/): 

| Number of Requests | Value of the `X-Powered-By` Header |
|:---|:---|
| 3858515 | ASP.NET |
| 722266 | PleskLin |
| 120204 | W3 Total Cache/0.9.4.1 |
| 93821 | PHP/5.3.3 |
| 88617 | PHP/5.2.17 |
| 85279 | WAF/2.0 |
| 79098 | PHP/5.3.29 |
| 55817 | W3 Total Cache/0.9.4 |
| 45309 | PHP/5.3.28 |
| 40714 | Express |
| 36329 | Undertow/1 |
| 33041 | Servlet/2.5 JSP/2.1 |
| 29594 | PHP/5.4.36 |
| 27502 | PHP/5.4.35 |
| 25852 | UrlRewriter.NET 2.0.0 ASP.NET |
| 25131 | PHP/5.5.9-1ubuntu4.5 |
| 23518 | ASP.NET ARR/2.5 ASP.NET |
| 22910 | ASP.NET ASP.NET |
| 22361 | PHP/5.3.10-1ubuntu3.15 |


Query used:

  ```sql
SELECT count(*) AS number_of_requests, resp_x_powered_by AS x_powered_by_header_value
FROM [httparchive:runs.2015_02_01_requests]
WHERE resp_x_powered_by != ""
GROUP BY x_powered_by_header_value
ORDER BY number_of_requests DESC
```

**Comment by alrra** [comment]
Other notes: 

  * Total number of requests made by the HTTP Archive in the 01.02.2015 run: 46098453

     Query used:

     ```sql
SELECT count(*) AS number_of_requests
FROM [httparchive:runs.2015_02_01_requests]
```

  * Total number of requests made by the HTTP Archive in the 01.02.2015 run that have the `X-Powered-By` Header: 6533969

     Query used:
   
     ```sql
SELECT count(*) AS number_of_requests
FROM [httparchive:runs.2015_02_01_requests]
WHERE resp_x_powered_by !=""
```

**Comment by PrplHaz4** [comment]
@alrra eh, PHP/* is the worst offender in your list with `411433`

**Comment by alrra** [comment]
> eh, PHP/* is the worst offender in your list with 411433

@PrplHaz4  ?

**Comment by alrra** [comment]
Notes: 

  * ASP.NET usually coupled with IIS
  * ASP.NET also sets two additional headers (`X-AspNet-Version`, `X-AspNetMvc-Version`), but for the sake of not going too far into framework specific headers, we'll be sticking with just removing the `X-Powered-By` header
