### ISSUE TITLE
"Download the Zip archive" link is broken

### ISSUE THREAD

**Issue by fcherman** [h5bp/server-configs-apache#65]
"Download the zip archive" returns a 404 on https://github.com/h5bp/server-configs-apache. Link text (with broken URL) in context below:

## **Getting Started**
There are a few options for getting the Apache server configs:
• Download the zip archive (links to https://github.com/h5bp/server-configs-apache/releases/download/2.14.0/htaccess-2.14.0.zip)

**Comment by arthurvr** [comment]
Yeah, I was able to confirm that. Thanks for letting us know. @alrra Is there a reason you didn't attach the zip to the latest release?

**Comment by AD7six** [comment]
Fixed in https://github.com/h5bp/server-configs-apache/commit/f7bd43edbf705b11b808e2ceeec7a0cdac516d97

Reference: https://github.com/h5bp/server-configs-apache/issues/70
