### ISSUE TITLE
Conflict between deflate and include

### ISSUE THREAD

**Issue by highstrike** [h5bp/server-configs-apache#66]
Hi,

I'm trying to setup my website with both 

`AddOutputFilterByType DEFLATE "text/css"`

and

```apache
<FilesMatch "\.combined\.css$">
Options +Includes
AddOutputFilterByType INCLUDES text/css
SetOutputFilter INCLUDES
</FilesMatch>
```

My css is called `site.combined.css` and it works only if i have a single line in the file. So this works
`<!--#include file="css/layout/reset.css" -->`

As soon as i put another line in it, it wont work anymore. So this doesn't work.
`<!--#include file="css/layout/reset.css" -->`
`<!--#include file="css/cake.css" -->`

I've narrowed it down to the deflate. If i remove the deflate from `text/css` then it will include and concatenate both files correctly.

I'm on Windows with Apache 2.4.9
Thanks!

**Comment by LeoColomb** [comment]
Is this still occurs?

**Comment by highstrike** [comment]
no clue man, i've since been using a custom combiner and minification script to handle my css and js files :)

**Comment by LeoColomb** [comment]
OK, then as I'm having trouble reproducing, I'm closing this issue.
But please _re-open_ if it still occurs.

**Comment by highstrike** [comment]
cool, thanks for the reply 👍
