### ISSUE TITLE
RFE: add composer install method

### ISSUE THREAD

**Issue by drAlberT** [h5bp/server-configs-apache#71]
May be nice to have it being installed via composer too :)

**Comment by AD7six** [comment]
I don't think that's a good idea - this isn't a php repo, and it means one-more-thing to manage/maintain.

**Comment by arthurvr** [comment]
> I don't think that's a good idea - this isn't a php repo, and it means one-more-thing to manage/maintain.

Agreed.

**Comment by drAlberT** [comment]
@AD7six you are right .. this is *not* a PHP repo 

But, as far as I can see this is neither a nodejs repo too .. uhmm so why Bower? requires Node and npm and Git.

**Comment by drAlberT** [comment]
ah ok .. closed in a few seconds .. I understand

**Comment by AD7six** [comment]
> so why Bower?

Bower is commonly used for managing frontend assets whereas composer is not; supporting composer also means supporting an ever-expanding list of not-really-related build tools. If you want it though, feel free to create it.

**Comment by drAlberT** [comment]
@AD7six  uhmm .. what am I missing? is apache configuration "frontend asset"?

I got your point .. ok

**Comment by arthurvr** [comment]
> @AD7six uhmm .. what am I missing? is apache configuration "frontend asset"?

No, but many developers handle it like being one. A common usecase of the npm version is what [WSK](https://github.com/google/web-starter-kit/blob/9bfe849535ad2d5b474198f7f6544c96934e375e/gulpfile.babel.js#L64) does for example.
