### ISSUE TITLE
Syntax Highlight .conf files as ApacheConf for GitHub and/or Vim

### ISSUE THREAD

**Issue by hatzopoulos** [h5bp/server-configs-apache#75]
I thought it would be nice for this repo to enable ApacheConf syntax highlighting on all the *.conf files in the repository.

As far as I know, there are two ways to accomplish this:

(1) Rename all the `.conf` files to `.apacheconf` to be in line with [github/linguist](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml#L156-L165) and then refactor the build scripts with the new extensions. Although this change could likely upset a few people's forks. [Here's a branch of this change](https://github.com/hatzopoulos/server-configs-apache/tree/apacheconf-files) (subsequently going this way wouldn't need the .gitattributes PR I made earlier)

or (2) prepend to all .conf files something like below, although perhaps `vim: syntax=apache` is not really needed. Going this route though, we would have to strip out the vim modelines in the build process.

``` apache
# vim: set filetype=apache:
# vim: syntax=apache
```

Let me know if interested. Related to https://github.com/h5bp/server-configs-apache/pull/74

**Comment by leek** [comment]
This was fixed in c6fa83e37e31f1ec8db0f885d5288c5652fdfaea, right?

**Comment by XhmikosR** [comment]
Is this still valid? I seem the .conf files being highlighted just fine now.

**Comment by leek** [comment]
**@XhmikosR:** I'm seeing the .conf files with highlighting now as well. This can probably be closed.
