### ISSUE TITLE
unused mobile directories/subdomains and common mistyping

### ISSUE THREAD

**Issue by Nick-Levinson** [h5bp/server-configs-apache#76]
I gather that, because some websites deal with mobile design by creating separate directories for content formatted to fit (while others use responsive CSS), some users or user agents might attempt to visit such directories. For responsive design, I've seen advice to redirect visits to certain subdomains and directories to the home page. For directories, since redirection is handled in the .htaccess file (my host runs Apache), I've added something like the following to mine:

RedirectPermanent /i http://example.com
RedirectPermanent /mobile http://example.com
RedirectPermanent /mobi http://example.com

I added /mobi because, if the TLD *.mobi grows in use, people may search for that as a directory, even though erroneous, so we may as well catch it in <.htaccess>.

Perhaps this should be added to H5BP's model .htaccess file, as an option for either commenting out or decommenting.

The third-level domains m and wap (as in m.example.com and wap.example.com) could be handled for the same reason by setting them up as aliases and perhaps that should be suggested somewhere in H5BP's documentation.

I forgot where I saw the advice, so I don't know whom to credit.

Firefox responds to failed attempts to reach Web addresses by suggesting proofreading one's typing, giving "ww.example.com" as the illustration. So I added that as an alias at my host. If Firefox is right to to give that error primacy, maybe it's common, and it should be added to H5BP's documentation as a suggestion.

This was originally suggested at https://github.com/h5bp/html5-boilerplate/issues/1710 and moving here was invited.

**Comment by LeoColomb** [comment]
This is really old, will raise too many false positives, and maybe against any standard...
