### ISSUE TITLE
Failed to load resource: net::ERR_CONTENT_LENGTH_MISMATCH

### ISSUE THREAD

**Issue by fazliddin** [h5bp/server-configs-apache#77]
Hi, I use header expiration settings, in every 3-4 month my bootstrap.css file gets unloadable and chrome shows error: Failed to load resource: net::ERR_CONTENT_LENGTH_MISMATCH. Domain: http://xabardor.uz

**Comment by fazliddin** [comment]
look at end of http://xabardor.uz/themes/simple-blue/css/bootstrap.css

**Comment by XhmikosR** [comment]
I don't think this is related to this repo.

If you have more info that that's the case comment again here.
