### ISSUE TITLE
Add sample preload/prefetch header for webfonts commented out in .htaccess

### ISSUE THREAD

**Issue by richbradshaw** [h5bp/server-configs-apache#81]
e.g.

```
Link: <https://example.com/font.woff>; rel=preload; as=font
```

Maybe for google web fonts as an example, as they are common.

This is likely to be a common technique in coming years, and I expect many people will be interested to know the best approach to this.

Doing it as a meta element in html isn't as performant, as the page needs to be at least downloaded and parsed, whereas assumedly the header will be dealt with earlier.

Perhaps two examples - one for where the font files are known (e.g. bootstraps Glyphicons from a CDN) and one for where the font files aren't known (Google Web Fonts), but the CSS file is.

This could be commented out, much like the other, similar components.

**Comment by LeoColomb** [comment]
I think this is too site specific to be included in these `.htaccess` guidelines, even if commented out by default.
This might generate too many bad user configurations.

**Comment by XhmikosR** [comment]
Yup, agreed.
