### ISSUE TITLE
HTTP Public Key Pinning (HPKP)?

### ISSUE THREAD

**Issue by Schweinepriester** [h5bp/server-configs-apache#82]
How about integrating HPKP (commented out and with placeholders)?

E.g.

``` apache
# Header set Public-Key-Pins "pin-sha256=\"XXX\"; pin-sha256=\"YYY\"; max-age=ZZZ"
```

Links:
- https://en.wikipedia.org/wiki/HTTP_Public_Key_Pinning
- https://developer.mozilla.org/en-US/docs/Web/Security/Public_Key_Pinning
- http://caniuse.com/#feat=publickeypinning
- https://raymii.org/s/articles/HTTP_Public_Key_Pinning_Extension_HPKP.html
- http://blog.rlove.org/2015/01/public-key-pinning-hpkp.html

Maybe even mentioning e.g. https://report-uri.io/, which has handy (insecure?) tools, but most important a service for reporting. Don't want to endorse it or something, just mentioning it.

**Comment by XhmikosR** [comment]
I'd like to see info about HPKP being added too.

**Comment by Llbe** [comment]
I think a warning should be added together with HPKP, _to handle it carefully_.

https://www.smashingmagazine.com/be-afraid-of-public-key-pinning/

**Comment by XhmikosR** [comment]
I think HPKP is mostly dead nowadays, due to its nature, so I don't think we should bother.

@LeoColomb thoughts?

**Comment by LeoColomb** [comment]
Agreed.
Also, I think HPKP is both too specific for each case and very sensitive. Every resource or material I found about it has warnings everywhere.

I would not recommend to include it here.
