### ISSUE TITLE
Expires vs Cache-Control max-age

### ISSUE THREAD

**Issue by joeyhoer** [h5bp/server-configs-apache#85]
I've looked through the issues and haven't seen this mentioned before. It seems like `Cache-Control` is the new recommendation for HTTP1.1. Is there a reason we are still using `Expires` for caching?

https://developers.google.com/speed/docs/insights/LeverageBrowserCaching

**Comment by joeyhoer** [comment]
It appears that [`mod_expires`](http://httpd.apache.org/docs/current/mod/mod_expires.html) "controls the setting of the Expires HTTP header and the max-age directive of the Cache-Control HTTP header in server responses".

**Comment by hatzopoulos** [comment]
That is correct. Example, loading a png file with

```apacheconf
ExpiresActive on
ExpiresByType image/png  "access plus 1 day"
```

Would produce response headers similar to the following

Date: Tue, 17 Nov 2015 00:19:25 GMT
Last-Modified: Tue, 17 Nov 2015 00:00:12 GMT
**Cache-Control: max-age=86400**
**Expires: Wed, 18 Nov 2015 00:19:25 GMT**
Content-Length: 3482
Content-Type: image/png
Server: Apache/2.4.17 (Win32) PHP/5.6.14

**Comment by alrra** [comment]
> It appears that [`mod_expires`](http://httpd.apache.org/docs/current/mod/mod_expires.html) "controls the setting of the Expires HTTP header **AND** the max-age directive of the Cache-Control HTTP header in server responses".

@joeyhoer You pretty much answered your own question. :)

**Comment by joeyhoer** [comment]
When you're right, you're right.

Wondering if there is any value in adding something like:

    Header append Cache-Control "public, must-revalidate"

Especially for media.
