### ISSUE TITLE
"Accept-EncodXng" ?

### ISSUE THREAD

**Issue by AntonLee** [h5bp/server-configs-apache#86]
Shouldn't it be "Accept-Encoding" in server-configs-apache/src/web_performance/compression.conf at line 12?

**Comment by alrra** [comment]
> Shouldn't it be "Accept-Encoding" in server-configs-apache/src/web_performance/compression.conf at line 12?

@AntonLee Yes, see: https://developer.yahoo.com/blogs/ydn/pushing-beyond-gzipping-25601.html

**Comment by AntonLee** [comment]
ok. My bad. Thanks for the link.
19.11.2015 13:19 пользователь "Cătălin Mariș" <notifications@github.com>
написал:

**Comment by alrra** [comment]
> ok. My bad. Thanks for the link.

@AntonLee No problem at all!
