### ISSUE TITLE
Proposal: Customizable builds?

### ISSUE THREAD

**Issue by tomkyle** [h5bp/server-configs-apache#89]
The build.sh script concats a number of ".conf" modules, some of which are commented out. So each time a new version is released, developers will copy the dist/.htaccess to their project root and will have to scroll through and seek the modules they last time "commented in" again (or vice versa), e.g. the HSTS section. Would it not be fine if we could pass a "build configuration" to the build script?

A simple config file could roughly look like this, e.g. as an bash include:

``` bash
# build.conf.inc

declare -A modules
# true:  An active module
# false: module to be commented out
modules["src/cross-origin/requests.conf"]=false
modules["src/cross-origin/images.conf"]=true
modules["src/cross-origin/resource_timing.conf"]=true
modules["src/cross-origin/web_fonts.conf"]=false
# ...
```

The `build.sh` script would then use a tweaked insert function, for example:

``` bash
# Import configuration in "modules" var, i.e.
# fill OPTIONS with CLI param $1 
# or default to build.conf.inc 
source $OPTIONS

# Includes or "includes-and-comments-out":
insert_file_if() {
    if [ ${modules["$1"]} = true ]; then
        insert_file "$1" "$2"
    else
        insert_file_comment_out "$1" "$2"
    fi
}

# Uses new insert_file_if function:
create_htaccess() {
    insert_header "cross-origin" "$file"
    insert_line "" "$file"
    insert_file_if "src/cross-origin/requests.conf" "$file"
    insert_line "" "$file"
    insert_file_if "src/cross-origin/images.conf" "$file"
    # ...
}
```

What do you think?

**Comment by LeoColomb** [comment]
Very interesting! Good idea!
Could you make a PR? 😃

**Comment by tomkyle** [comment]
I'll do my very best :-D (I'm afraid though, I'll have to ask my time machine, after 20 months and several HD tidyups)

**Comment by tomkyle** [comment]
Sorry folks, I have not forgotten you. ...putting this back on stack.

**Comment by LeoColomb** [comment]
@tomkyle No problem, take your time (even if I can't wait to see your amazing PR!) 😺 👍

**Comment by LeoColomb** [comment]
Thanks a lot for your impressive contribution @tomkyle, very appreciated! 🎉 👍

**Comment by tomkyle** [comment]
It was a pleasure :-) Thank you @LeoColomb for the advice here and there!
