### ISSUE TITLE
www or bare in .htaccess or at host

### ISSUE THREAD

**Issue by Nick-Levinson** [h5bp/server-configs-apache#92]
Although preferring bare or www, it's better to leave both options commented out if the host also provides redirection or aliasing between the two. This is relevant to v5.3.0 > .htaccess > Rewrites > "Suppressing / Forcing the 'www.' at the beginning of URLs". When I had the option preferring naked decommented and forgot I also had the corresponding option set in the host's interface, trying to visit www got an endless loop and my host's (not my) error page. I use my host's method now.

With respect to preferring www, for which my host argues, I suggest adding explanatory URLs for it to the model .htaccess file: for tech reasons http://www.yes-www.org/why-use-www/ and for lay reasons http://www.yes-www.org/, both as accessed Feb. 6, 2016. The technical reasons appear to have some validity and website admins should consider them. The file already offers an explanatory URL favoring the bare form.

**Comment by LeoColomb** [comment]
Could be very useful to have the option, you're right. Maybe can be involved within #89?
