### ISSUE TITLE
Include query strings in redirection?

### ISSUE THREAD

**Issue by stuff-and-nonsense** [h5bp/server-configs-apache#96]
Redirection looses query strings:

http://www.example.com/foo#bar → http://example.com/foo (no #bar)

Can be added with %{QUERY_STRING}. Is there a reason for not keeping them?

This is with respect to:
server-configs-apache/src/rewrites/rewrite_www.conf

**Comment by hatzopoulos** [comment]
The portion after the hash/pound (`#`) sign is not part of the query string. It's has been called a [fragment or a named anchor](https://developer.mozilla.org/en-US/Learn/Common_questions/What_is_a_URL).

**Comment by stuff-and-nonsense** [comment]
Good catch. The fragment/named anchor seems to be included in REQUEST_URI as well as the QUERY_STRING. I thought:

http://www.example.com/foo?bar → http://example.com/foo (no ?bar)

was not going to pass as the Apache documentation reads:

REQUEST_URI
    The path component of the requested URI, such as "/index.html". This notably excludes the query string which is available as its own variable named QUERY_STRING.

http://httpd.apache.org/docs/current/mod/mod_rewrite.html#rewritecond

Perhaps the Apache documentation is out of whack.

Thanks, hatzopoulos.
