### ISSUE TITLE
True type font (.ttf) media/mime type change?

### ISSUE THREAD

**Issue by stuff-and-nonsense** [h5bp/server-configs-apache#97]
It looks like the mime type for true type fonts (.ttf) might have changed from application/x-font-ttf to application/font-sfnt.

I do not see a safari/webkit console warning for this on a web page, but do if you directly reference the font in the address bar.

Ref:
https://www.iana.org/assignments/media-types/application/font-sfnt

**Comment by LeoColomb** [comment]
Can be closed since #114
