### ISSUE TITLE
Implement CSP standard based on browser support

### ISSUE THREAD

**Issue by magicdude4eva** [h5bp/server-configs-apache#99]
Refer to http://content-security-policy.com/ for browser support.

It would be better to have BrowserMatch directives in the configuration to conditionally support CSP levels as supported by the various browsers.

This would then allow that we could serve "frame-src" to CSP1 supported browsers and "child-src" to CSP2.

I am not sure if it is possible to use environment variables to make the HTTP configuration more readable as HTTP config only has limited line-break support.

Pseudo code like this (CSP-2 = Chrome 40+, Firefox 31+ / CSP-1 = Chome 25+, Firefox 23+, Safari 7+, Edge 12)

```
if (($user_agent == 'chrome' && $version > 40) || ($user_agent == 'firefox' && $version > 31)) {
  header("X-Content-Security-Policy: $csp2");
} else if (($user_agent == 'chrome' && $version > 25) || ($user_agent == 'safari' && $version > 7) || ($user_agent == 'Edge12')) {
  // use frame-src instead of child-src / no support for form-action
  header("X-Content-Security-Policy: $csp1");
} else {
  // no CSP policy
}
```

Header set Content-Security-Policy-Report-Only " \
default-src 'self'; \
script-src 'self' *.example.com 'unsafe-inline' 'unsafe-eval' \
http://www.mydomain.com \
*.googletagmanager.com pagead2.googlesyndication.com ajax.googleapis.com apis.google.com www.google.com https://www.gstatic.com www.google-analytics.com www.googleadservices.com \
api.pinterest.com \
connect.facebook.net graph.facebook.com \
bam.nr-data.net \
bat.bing.com \
http://www.linkedin.com \
seal.verisign.com \
js-agent.newrelic.com \
my.nanorep.com \
platform.twitter.com ; \
child-src 'self' platform.twitter.com staticxx.facebook.com www.facebook.com my.nanorep.com web.facebook.com https://www.google.com https://googleads.g.doubleclick.net; \
img-src \* data:; \
style-src 'self' 'unsafe-inline' fonts.googleapis.com; \
font-src \* data:; \
form-action 'self' http://example.com; \
object-src 'self' pagead2.googlesyndication.com; \
connect-src 'self' www.google-analytics.com http://s3.amazonaws.com/publisher_configurations.shareaholic/ https://api.cloudinary.com; \
report-uri https://XXXX.report-uri.io/r/default/csp/reportOnly;"

```

Another headache with CSP and Safari is that Safari requires http and https for domains.
```

**Comment by LeoColomb** [comment]
Your suggestion is interesting, but it will not be possible/necessary:

* Distinct each browser is very hard if not impossible with the `.htaccess`.
* CSP-2 is backward compatible with CSP-1, only a few additions. CSP-1-only browsers don't fail but ignore unknown directives. (see https://content-security-policy.com/)
